MODULE TYPES

! Definitions of various derived data types

USE PRECISION_PARAMETERS
USE GLOBAL_CONSTANTS, ONLY : NULL_BOUNDARY,NEUMANN, MAX_SPECIES,IAXIS,JAXIS,KAXIS,MAX_DIM,NOD1,NOD2,IBM_MAX_WSTRIANG_SEG

IMPLICIT NONE

TYPE LAGRANGIAN_PARTICLE_CLASS_TYPE
   CHARACTER(LABEL_LENGTH) :: ID,SPEC_ID,DEVC_ID='null',CTRL_ID='null',QUANTITIES(10),SMOKEVIEW_BAR_LABEL(10),&
                    SURF_ID='null',PROP_ID='null',&
                    RADIATIVE_PROPERTY_TABLE_ID='null',CNF_RAMP_ID='null',DISTRIBUTION='ROSIN-RAMMLER-LOGNORMAL',&
                    BREAKUP_DISTRIBUTION='ROSIN-RAMMLER-LOGNORMAL',BREAKUP_CNF_RAMP_ID='null'
   CHARACTER(60) :: SMOKEVIEW_LABEL(10),QUANTITIES_SPEC_ID(10)
   REAL(EB) :: HEAT_OF_COMBUSTION,ADJUST_EVAPORATION, &
               LIFETIME,DIAMETER,MINIMUM_DIAMETER,MAXIMUM_DIAMETER,GAMMA,KILL_RADIUS,KILL_MASS, &
               TMP_INITIAL,SIGMA,VERTICAL_VELOCITY,HORIZONTAL_VELOCITY,DRAG_COEFFICIENT(3), &
               SURFACE_TENSION,BREAKUP_RATIO,BREAKUP_GAMMA,BREAKUP_SIGMA,DENSE_VOLUME_FRACTION, PERMEABILITY(3),&
               REAL_REFRACTIVE_INDEX,COMPLEX_REFRACTIVE_INDEX,TOL_INT,DENSITY=-1._EB,FTPR,FREE_AREA_FRACTION,&
               POROUS_VOLUME_FRACTION,MEAN_DROPLET_VOLUME=0._EB
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: R_CNF,CNF,CVF,BREAKUP_R_CNF,BREAKUP_CNF,BREAKUP_CVF,W_CNF,R50,LAMBDA,SOLID_ANGLE
   REAL(EB), ALLOCATABLE, DIMENSION(:,:) :: WQABS,WQSCA
   INTEGER :: SAMPLING,N_QUANTITIES,QUANTITIES_INDEX(10),QUANTITIES_Y_INDEX(10)=-1,QUANTITIES_Z_INDEX(10)=-1,ARRAY_INDEX=0,&
              RGB(3),RADIATIVE_PROPERTY_INDEX=0,SURF_INDEX=0,DRAG_LAW=1,DEVC_INDEX=0,CTRL_INDEX=0,PROP_INDEX=-1,&
              ORIENTATION_INDEX=0,N_ORIENTATION,Z_INDEX=-1,N_STRATA=7, &
              Y_INDEX=-1,CNF_RAMP_INDEX=-1,BREAKUP_CNF_RAMP_INDEX=-1,N_STORAGE_REALS,N_STORAGE_INTEGERS,N_STORAGE_LOGICALS
   INTEGER,  ALLOCATABLE, DIMENSION(:) :: IL_CNF,IU_CNF
   LOGICAL :: STATIC=.FALSE.,MASSLESS_TRACER=.FALSE.,MASSLESS_TARGET=.FALSE.,LIQUID_DROPLET=.FALSE.,SOLID_PARTICLE=.FALSE., &
              MONODISPERSE=.FALSE.,TURBULENT_DISPERSION=.FALSE.,BREAKUP=.FALSE.,CHECK_DISTRIBUTION=.FALSE.,FUEL=.FALSE., &
              PERIODIC_X=.FALSE.,PERIODIC_Y=.FALSE.,PERIODIC_Z=.FALSE.,SECOND_ORDER_PARTICLE_TRANSPORT=.FALSE.,DUCT_PARTICLE=.FALSE.
END TYPE LAGRANGIAN_PARTICLE_CLASS_TYPE

TYPE (LAGRANGIAN_PARTICLE_CLASS_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: LAGRANGIAN_PARTICLE_CLASS

! Note: If you change the number of scalar variables in ONE_D_M_AND_E_XFER_TYPE, adjust the numbers below

INTEGER, PARAMETER :: N_ONE_D_SCALAR_REALS=13,N_ONE_D_SCALAR_INTEGERS=9,N_ONE_D_SCALAR_LOGICALS=2

TYPE ONE_D_M_AND_E_XFER_TYPE
   REAL(EB), POINTER, DIMENSION(:) :: TMP,LAYER_THICKNESS,X,MASSFLUX_ACTUAL,MASSFLUX
   REAL(EB), POINTER, DIMENSION(:,:) :: RHO,ILW
   INTEGER, POINTER, DIMENSION(:) :: N_LAYER_CELLS
   INTEGER, POINTER :: ARRAY_INDEX,STORAGE_INDEX,II,JJ,KK,IIG,JJG,KKG,IOR
   REAL(EB), POINTER :: AREA,RAREA,HEAT_TRANS_COEF,QCONF,QRADIN,QRADOUT,EMISSIVITY,AREA_ADJUST,T_IGN,TMP_F,TMP_B,UW,UWS, &
                        HEAT_TRANS_COEF_B,QCONB,QRADIN_B,QRADOUT_B
   LOGICAL, POINTER :: BURNAWAY,CHANGE_THICKNESS
END TYPE ONE_D_M_AND_E_XFER_TYPE

! Note: If you change the number of scalar variables in LAGRANGIAN_PARTICLE_TYPE, adjust the numbers below

INTEGER, PARAMETER :: N_PARTICLE_SCALAR_REALS=17,N_PARTICLE_SCALAR_INTEGERS=6,N_PARTICLE_SCALAR_LOGICALS=2

TYPE LAGRANGIAN_PARTICLE_TYPE
   TYPE (ONE_D_M_AND_E_XFER_TYPE) :: ONE_D
   LOGICAL, POINTER :: SHOW,SPLAT
   REAL(EB), POINTER :: X,Y,Z,U,V,W,PWT,ACCEL_X,ACCEL_Y,ACCEL_Z,RE,MASS,T_INSERT,DX,DY,DZ,M_DOT
   INTEGER, POINTER :: TAG,ARRAY_INDEX,STORAGE_INDEX,CLASS_INDEX,ORIENTATION_INDEX,WALL_INDEX,FACE_INDEX,DUCT_INDEX,DUCT_CELL_INDEX
END TYPE LAGRANGIAN_PARTICLE_TYPE


TYPE STORAGE_TYPE
   INTEGER :: N_STORAGE_SLOTS=0,NEXT_AVAILABLE_SLOT=1
   REAL(EB), ALLOCATABLE, DIMENSION(:,:) :: REALS
   INTEGER, ALLOCATABLE, DIMENSION(:,:) :: INTEGERS
   LOGICAL, ALLOCATABLE, DIMENSION(:,:) :: LOGICALS
END TYPE STORAGE_TYPE

! Note: If you change the number of scalar variables in WALL_TYPE, adjust the numbers below

INTEGER, PARAMETER :: N_WALL_SCALAR_REALS=19,N_WALL_SCALAR_INTEGERS=12,N_WALL_SCALAR_LOGICALS=0

TYPE WALL_TYPE
   TYPE (ONE_D_M_AND_E_XFER_TYPE) :: ONE_D
   REAL(EB), POINTER, DIMENSION(:) :: A_LP_MPUA,AWM_AEROSOL,LP_CPUA,LP_MPUA,RHODW,VEG_FUELMASS_L,VEG_MOISTMASS_L,VEG_TMP_L,ZZ_F
   REAL(EB), POINTER :: AW,DUWDT,EW,KW,Q_LEAK,RAW,RDN,RHO_F,TMP_F_GAS,U_TAU,UVW_GHOST,UW0,V_DEP,VEG_HEIGHT,VEL_ERR_NEW,XW,Y_PLUS,&
                        YW,ZW
   INTEGER, POINTER :: BACK_INDEX,BACK_MESH,BOUNDARY_TYPE,NODE_INDEX,OBST_INDEX,PRESSURE_BC_INDEX,PRESSURE_ZONE,SURF_INDEX,&
                       SURF_INDEX_ORIG,VENT_INDEX,WALL_INDEX,LAPLACE_BC_INDEX
END TYPE WALL_TYPE

TYPE EXTERNAL_WALL_TYPE
   INTEGER :: NOM,NIC_MIN,NIC_MAX,IIO_MIN,IIO_MAX,JJO_MIN,JJO_MAX,KKO_MIN,KKO_MAX
   REAL(EB) :: AREA_RATIO
END TYPE EXTERNAL_WALL_TYPE

TYPE EXPOSED_WALL_TYPE
   REAL(EB) :: QRADIN,TMP_GAS
END TYPE EXPOSED_WALL_TYPE

TYPE SPECIES_TYPE
   REAL(EB) :: MW=0._EB,YY0=0._EB,RCON,MAXMASS,MASS_EXTINCTION_COEFFICIENT=0._EB,&
               SPECIFIC_HEAT=-1._EB,REFERENCE_ENTHALPY=-1._EB,&
               REFERENCE_TEMPERATURE,MU_USER=-1._EB,K_USER=-1._EB,D_USER=-1._EB,EPSK=-1._EB,SIG=-1._EB,PR_USER=-1._EB,&
               FLD_LETHAL_DOSE=0._EB,FIC_CONCENTRATION=0._EB,PR_GAS,&
               SPECIFIC_HEAT_LIQUID=-1,DENSITY_LIQUID,HEAT_OF_VAPORIZATION=-1._EB,&
               H_F,H_V_REFERENCE_TEMPERATURE=-1._EB,H_V_CORRECTOR=0._EB ,TMP_V=-1._EB,TMP_MELT=-1._EB,ATOMS(118)=0._EB,&
               MEAN_DIAMETER=1.E-6_EB,CONDUCTIVITY_SOLID,DENSITY_SOLID,BETA_LIQUID,MU_LIQUID,K_LIQUID,PR_LIQUID
   LOGICAL ::  ISFUEL=.FALSE.,LISTED=.FALSE.,AGGLOMERATING=.FALSE.,EXPLICIT_H_F=.FALSE.
   CHARACTER(LABEL_LENGTH) :: ID,RAMP_CP,RAMP_CP_L,RAMP_K,RAMP_MU,RAMP_D,RADCAL_ID,RAMP_G_F,PROP_ID
   CHARACTER(100) :: FORMULA
   INTEGER :: MODE=2,RAMP_CP_INDEX=-1,RAMP_CP_L_INDEX=-1,RAMP_K_INDEX=-1,RAMP_MU_INDEX=-1,RAMP_D_INDEX=-1,RADCAL_INDEX=-1,&
              RAMP_G_F_INDEX=-1,AWM_INDEX=-1
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: H_V,C_P_L,C_P_L_BAR,H_L

END TYPE SPECIES_TYPE

TYPE (SPECIES_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: SPECIES

TYPE SPECIES_MIXTURE_TYPE
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: MASS_FRACTION,VOLUME_FRACTION
   REAL(EB) :: MW , RCON, ZZ0=0._EB, MASS_EXTINCTION_COEFFICIENT=0._EB,ADJUST_NU=1._EB,ATOMS(118)=0._EB,MEAN_DIAMETER,&
               SPECIFIC_HEAT=-1._EB,REFERENCE_ENTHALPY=-2.E20_EB,&
               REFERENCE_TEMPERATURE,MU_USER=-1._EB,K_USER=-1._EB,D_USER=-1._EB,PR_USER=-1._EB,EPSK=-1._EB,SIG=-1._EB,&
               FLD_LETHAL_DOSE=0._EB,FIC_CONCENTRATION=0._EB,&
               DENSITY_SOLID,CONDUCTIVITY_SOLID,H_F=-1.E30_EB
   CHARACTER(LABEL_LENGTH), ALLOCATABLE, DIMENSION(:) :: SPEC_ID
   CHARACTER(LABEL_LENGTH) :: ID='null',RAMP_CP,RAMP_CP_L,RAMP_K,RAMP_MU,RAMP_D,RAMP_G_F
   CHARACTER(100) :: FORMULA='null'
   INTEGER :: AWM_INDEX = -1,RAMP_CP_INDEX=-1,SINGLE_SPEC_INDEX=-1,RAMP_K_INDEX=-1,RAMP_MU_INDEX=-1,RAMP_D_INDEX=-1,&
              RAMP_G_F_INDEX=-1
   LOGICAL :: DEPOSITING=.FALSE.,VALID_ATOMS=.TRUE.,EVAPORATING=.FALSE.
END TYPE SPECIES_MIXTURE_TYPE

TYPE (SPECIES_MIXTURE_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: SPECIES_MIXTURE

TYPE REACTION_TYPE
   CHARACTER(LABEL_LENGTH) :: FUEL,OXIDIZER,PRODUCTS,ID,RAMP_FS,TABLE_FS,RAMP_CHI_R
   CHARACTER(LABEL_LENGTH), ALLOCATABLE, DIMENSION(:) :: SPEC_ID_NU,SPEC_ID_NU_READ,SPEC_ID_N_S,SPEC_ID_N_S_READ
   REAL(EB) :: C,H,N,O,EPUMO2,HEAT_OF_COMBUSTION,HOC_COMPLETE,A,A_PRIME,A_PRIME_FAST,A_IN,E,E_IN,K,&
               Y_O2_INFTY,Y_N2_INFTY=0._EB,MW_FUEL,MW_SOOT,&
               CO_YIELD,SOOT_YIELD,H2_YIELD, SOOT_H_FRACTION,RHO_EXPONENT,RHO_EXPONENT_FAST,CRIT_FLAME_TMP,&
               NU_O2=0._EB,NU_N2=0._EB,NU_H2O=0._EB,NU_CO2=0._EB,NU_CO=0._EB,NU_SOOT=0._EB,S=0._EB
   REAL(EB) :: AUTO_IGNITION_TEMPERATURE=0._EB,THRESHOLD_TEMP=0._EB,N_T=0._EB,&
               FLAME_SPEED=-1._EB,FLAME_SPEED_EXPONENT=0._EB,FLAME_SPEED_TEMPERATURE=-1._EB,&
               TURBULENT_FLAME_SPEED_ALPHA=1._EB,TURBULENT_FLAME_SPEED_EXPONENT=2._EB,CHI_R
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: NU,NU_READ,NU_SPECIES,N_S,N_S_READ,NU_MW_O_MW_F
   INTEGER :: FUEL_SMIX_INDEX=-1,AIR_SMIX_INDEX=-1,MODE,N_SMIX,N_SPEC,RAMP_FS_INDEX=0,TABLE_FS_INDEX=0,ALT_INDEX=-1,&
              RAMP_CHI_R_INDEX=0
   LOGICAL :: IDEAL,CHECK_ATOM_BALANCE,FAST_CHEMISTRY=.FALSE.,REVERSE=.FALSE.,THIRD_BODY=.FALSE.
   CHARACTER(100) :: FYI='null'
   CHARACTER(255) :: EQUATION
   CHARACTER(100) :: FWD_ID,ALT_REAC_ID
END TYPE REACTION_TYPE

TYPE (REACTION_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: REACTION

TYPE MATERIAL_TYPE
   REAL(EB) :: K_S,C_S,RHO_S,EMISSIVITY,DIFFUSIVITY,KAPPA_S,MOISTURE_FRACTION,TMP_BOIL,POROSITY
   INTEGER :: PYROLYSIS_MODEL
   CHARACTER(LABEL_LENGTH) :: ID
   CHARACTER(LABEL_LENGTH) :: RAMP_K_S,RAMP_C_S
   INTEGER :: N_REACTIONS,PROP_INDEX=-1
   INTEGER, DIMENSION(MAX_REACTIONS) :: N_RESIDUE
   INTEGER, DIMENSION(MAX_MATERIALS,MAX_REACTIONS) :: RESIDUE_MATL_INDEX
   INTEGER, DIMENSION(3) :: RGB
   REAL(EB), DIMENSION(MAX_REACTIONS) :: TMP_REF,TMP_IGN,TMP_THR,RATE_REF,THR_SIGN
   REAL(EB), DIMENSION(MAX_MATERIALS,MAX_REACTIONS) :: NU_RESIDUE
   REAL(EB), DIMENSION(MAX_REACTIONS) :: A,E,H_R,N_S,N_T,N_O2,GAS_DIFFUSION_DEPTH
   REAL(EB), DIMENSION(MAX_REACTIONS) :: HEATING_RATE,PYROLYSIS_RANGE,HEAT_OF_COMBUSTION,TOL_INT
   REAL(EB), ALLOCATABLE, DIMENSION(:,:) :: NU_GAS,ADJUST_BURN_RATE
   REAL(EB), DIMENSION(MAX_SPECIES,MAX_REACTIONS) :: NU_SPEC
   LOGICAL, DIMENSION(MAX_REACTIONS) :: PCR = .FALSE.
   LOGICAL :: ALLOW_SHRINKING, ALLOW_SWELLING
   CHARACTER(LABEL_LENGTH), DIMENSION(MAX_MATERIALS,MAX_REACTIONS) :: RESIDUE_MATL_NAME
   CHARACTER(LABEL_LENGTH), DIMENSION(MAX_SPECIES,MAX_REACTIONS) :: SPEC_ID
   CHARACTER(100) :: FYI='null'
END TYPE MATERIAL_TYPE

TYPE (MATERIAL_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: MATERIAL

TYPE SURFACE_TYPE
   REAL(EB) :: TMP_FRONT=-1._EB,TMP_BACK=-1._EB,VEL,VEL_GRAD,PLE,Z0,CONVECTIVE_HEAT_FLUX,NET_HEAT_FLUX, &
               VOLUME_FLOW,HRRPUA,MLRPUA,T_IGN,SURFACE_DENSITY,CELL_SIZE_FACTOR, &
               E_COEFFICIENT,TEXTURE_WIDTH,TEXTURE_HEIGHT,THICKNESS,EXTERNAL_FLUX, &
               DXF,DXB,MASS_FLUX_TOTAL,PARTICLE_MASS_FLUX,EMISSIVITY,MAX_PRESSURE, &
               TMP_IGN,H_V,LAYER_DIVIDE,ROUGHNESS,LENGTH=-1._EB,WIDTH=-1._EB, &
               DT_INSERT,H_FIXED=-1._EB,H_FIXED_B=-1._EB,HM_FIXED=-1._EB,EMISSIVITY_BACK,CONV_LENGTH,XYZ(3),FIRE_SPREAD_RATE, &
               MINIMUM_LAYER_THICKNESS,INNER_RADIUS=0._EB,MASS_FLUX_VAR=-1._EB,VEL_BULK,ZETA_FRONT=-1._EB, &
               AUTO_IGNITION_TEMPERATURE=1.E20_EB
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: DX,RDX,RDXN,X_S,DX_WGT,MF_FRAC,PARTICLE_INSERT_CLOCK
   REAL(EB), ALLOCATABLE, DIMENSION(:,:) :: RHO_0
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: MASS_FRACTION,MASS_FLUX,TAU,ADJUST_BURN_RATE
   INTEGER,  ALLOCATABLE, DIMENSION(:) :: RAMP_INDEX
   INTEGER, DIMENSION(3) :: RGB
   REAL(EB) :: TRANSPARENCY
   REAL(EB), DIMENSION(2) :: VEL_T
   INTEGER, DIMENSION(2) :: LEAK_PATH,DUCT_PATH
   INTEGER :: THERMAL_BC_INDEX,NPPC,SPECIES_BC_INDEX,VELOCITY_BC_INDEX,SURF_TYPE,N_CELLS_INI,N_CELLS_MAX, &
              PART_INDEX,PROP_INDEX=-1,RAMP_T_I_INDEX=-1
   INTEGER :: PYROLYSIS_MODEL,NRA,NSB
   INTEGER :: N_LAYERS,N_MATL
   INTEGER :: N_ONE_D_STORAGE_REALS,N_ONE_D_STORAGE_INTEGERS,N_ONE_D_STORAGE_LOGICALS
   INTEGER :: N_WALL_STORAGE_REALS,N_WALL_STORAGE_INTEGERS,N_WALL_STORAGE_LOGICALS
   INTEGER, DIMENSION(10) :: ONE_D_REALS_ARRAY_SIZE=0,ONE_D_INTEGERS_ARRAY_SIZE=0,ONE_D_LOGICALS_ARRAY_SIZE=0
   INTEGER, DIMENSION(10) :: WALL_REALS_ARRAY_SIZE=0,WALL_LOGICALS_ARRAY_SIZE=0
   INTEGER, ALLOCATABLE, DIMENSION(:) :: N_LAYER_CELLS,LAYER_INDEX,MATL_INDEX
   INTEGER, DIMENSION(MAX_LAYERS,MAX_MATERIALS) :: LAYER_MATL_INDEX
   INTEGER, DIMENSION(MAX_LAYERS) :: N_LAYER_MATL,N_LAYER_CELLS_MAX
   INTEGER, ALLOCATABLE, DIMENSION(:,:,:) :: RESIDUE_INDEX
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: MIN_DIFFUSIVITY
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: LAYER_THICKNESS,INTERNAL_HEAT_SOURCE
   REAL(EB), DIMENSION(MAX_LAYERS) :: LAYER_DENSITY, TMP_INNER, STRETCH_FACTOR
   CHARACTER(LABEL_LENGTH), ALLOCATABLE, DIMENSION(:) :: MATL_NAME
   CHARACTER(LABEL_LENGTH), DIMENSION(MAX_LAYERS,MAX_MATERIALS) :: LAYER_MATL_NAME
   REAL(EB), DIMENSION(MAX_LAYERS,MAX_MATERIALS) :: LAYER_MATL_FRAC
   LOGICAL :: BURN_AWAY,ADIABATIC,THERMALLY_THICK,INTERNAL_RADIATION,USER_DEFINED=.TRUE., &
              FREE_SLIP=.FALSE.,NO_SLIP=.FALSE.,SPECIFIED_NORMAL_VELOCITY=.FALSE.,SPECIFIED_TANGENTIAL_VELOCITY=.FALSE., &
              SPECIFIED_NORMAL_GRADIENT=.FALSE.,CONVERT_VOLUME_TO_MASS=.FALSE.,SPECIFIED_HEAT_SOURCE=.FALSE.,&
              THERMALLY_THICK_HT3D=.FALSE.
   INTEGER :: GEOMETRY,BACKING,PROFILE,HEAT_TRANSFER_MODEL=0
   CHARACTER(LABEL_LENGTH) :: PART_ID,RAMP_Q,RAMP_V,RAMP_T,RAMP_EF,RAMP_PART,RAMP_V_X,RAMP_V_Y,RAMP_V_Z,RAMP_T_I
   CHARACTER(LABEL_LENGTH), ALLOCATABLE, DIMENSION(:) :: RAMP_MF
   CHARACTER(60) :: ID,TEXTURE_MAP
   CHARACTER(100) :: FYI='null'

   ! Boundary vegetation
   LOGICAL  :: VEGETATION=.FALSE.,VEG_NO_BURN=.FALSE.,VEG_GROUND_ZERO_RAD=.TRUE., &
               VEG_LINEAR_DEGRAD,VEG_ARRHENIUS_DEGRAD
   INTEGER  :: NVEG_L
   REAL(EB) :: VEG_CHARFRAC,VEG_DRAG_INI,VEG_ELEMENT_DENSITY,VEG_HEIGHT,VEG_INITIAL_TEMP,VEG_LOAD, &
               VEG_MOISTURE,VEG_SVRATIO,VEG_PACKING,VEG_KAPPA,FIRELINE_MLR_MAX,VEG_GROUND_TEMP
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: VEG_FUEL_FLUX_L,VEG_MOIST_FLUX_L,VEG_DIVQNET_L
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: VEG_INCM_RADFCT_L,VEG_FINCM_RADFCT_L,VEG_FINCP_RADFCT_L
   !add index for mult veg
   REAL(EB), ALLOCATABLE, DIMENSION(:,:) :: VEG_SEMISSM_RADFCT_L,VEG_SEMISSP_RADFCT_L !add index for mult veg

   ! Level Set Firespread
   LOGICAL :: VEG_LSET_SPREAD,VEG_LSET_ELLIPSE,VEG_LSET_TAN2
   REAL(EB) :: VEG_LSET_IGNITE_T,VEG_LSET_ROS_HEAD,VEG_LSET_ELLIPSE_HEAD,VEG_LSET_QCON,VEG_LSET_ROS_FLANK,VEG_LSET_ROS_BACK, &
               VEG_LSET_WIND_EXP

   !Veg SAV and height (fuel depth) for Farsite emulation
   REAL(EB) :: VEG_LSET_SIGMA,VEG_LSET_HT,VEG_LSET_BETA

   !HTC Custom
   REAL(EB) :: C_FORCED_CONSTANT=0._EB,C_FORCED_PR_EXP=0._EB,C_FORCED_RE=0._EB,C_FORCED_RE_EXP=0._EB,C_HORIZONTAL,C_VERTICAL

END TYPE SURFACE_TYPE

TYPE (SURFACE_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: SURFACE

TYPE OMESH_TYPE
   REAL(EB), ALLOCATABLE, DIMENSION(:,:,:) :: MU,RHO,RHOS,U,V,W,US,VS,WS,H,HS,FVX,FVY,FVZ,D,DS,KRES,IL_S,IL_R
   REAL(EB), ALLOCATABLE, DIMENSION(:,:,:,:) :: ZZ,ZZS
   INTEGER, ALLOCATABLE, DIMENSION(:) :: BOUNDARY_TYPE,IIO_R,JJO_R,KKO_R,IOR_R,IIO_S,JJO_S,KKO_S,IOR_S
   INTEGER, ALLOCATABLE, DIMENSION(:) :: N_PART_ORPHANS,N_PART_ADOPT,EXPOSED_WALL_CELL_BACK_INDICES,WALL_CELL_INDICES_SEND
   INTEGER :: I_MIN_R=-10,I_MAX_R=-10,J_MIN_R=-10,J_MAX_R=-10,K_MIN_R=-10,K_MAX_R=-10,NIC_R=0,N_WALL_CELLS_SEND=0, &
              I_MIN_S=-10,I_MAX_S=-10,J_MIN_S=-10,J_MAX_S=-10,K_MIN_S=-10,K_MAX_S=-10,NIC_S=0,N_EXPOSED_WALL_CELLS=0
   INTEGER, DIMENSION(7) :: INTEGER_SEND_BUFFER,INTEGER_RECV_BUFFER
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: &
         REAL_SEND_PKG1,REAL_SEND_PKG2,REAL_SEND_PKG3,REAL_SEND_PKG4,REAL_SEND_PKG5,REAL_SEND_PKG6,REAL_SEND_PKG7,&
         REAL_RECV_PKG1,REAL_RECV_PKG2,REAL_RECV_PKG3,REAL_RECV_PKG4,REAL_RECV_PKG5,REAL_RECV_PKG6,REAL_RECV_PKG7
   TYPE (STORAGE_TYPE), ALLOCATABLE, DIMENSION(:) :: ORPHAN_PARTICLE_STORAGE,ADOPT_PARTICLE_STORAGE
   TYPE (EXPOSED_WALL_TYPE), ALLOCATABLE, DIMENSION(:) :: EXPOSED_WALL
END TYPE OMESH_TYPE

TYPE OBSTRUCTION_TYPE
   CHARACTER(LABEL_LENGTH) :: DEVC_ID='null',CTRL_ID='null',PROP_ID='null',MATL_ID='null'
   INTEGER, DIMENSION(-3:3) :: SURF_INDEX=0
   LOGICAL, DIMENSION(-3:3) :: SHOW_BNDF=.TRUE.
   INTEGER, DIMENSION(3) :: RGB=(/0,0,0/)
   INTEGER, DIMENSION(3) :: DIMENSIONS=0
   REAL(EB) :: TRANSPARENCY=1._EB,VOLUME_ADJUST=1._EB,BULK_DENSITY=-1._EB
   REAL(EB), DIMENSION(3) :: TEXTURE=0._EB
   REAL(EB) :: X1=0._EB,X2=1._EB,Y1=0._EB,Y2=1._EB,Z1=0._EB,Z2=1._EB,MASS=1.E6_EB
   REAL(EB), DIMENSION(3) :: FDS_AREA=-1._EB,INPUT_AREA=-1._EB,UNDIVIDED_INPUT_AREA=-1._EB
   INTEGER :: I1=-1,I2=-1,J1=-1,J2=-1,K1=-1,K2=-1,COLOR_INDICATOR=-1,TYPE_INDICATOR=-1,ORDINAL=0
   INTEGER :: DEVC_INDEX=-1,CTRL_INDEX=-1,PROP_INDEX=-1,DEVC_INDEX_O=-1,CTRL_INDEX_O=-1,MATL_INDEX=-1
   LOGICAL :: HIDDEN=.FALSE.,PERMIT_HOLE=.TRUE.,ALLOW_VENT=.TRUE.,CONSUMABLE=.FALSE.,REMOVABLE=.FALSE., &
              HOLE_FILLER=.FALSE.,NOTERRAIN=.FALSE.,OVERLAY=.TRUE.,HT3D=.FALSE.
END TYPE OBSTRUCTION_TYPE

TYPE GEOMETRY_TYPE
   CHARACTER(LABEL_LENGTH) :: ID='geom', SURF_ID='null', MATL_ID='null'
   LOGICAL :: COMPONENT_ONLY, IS_DYNAMIC=.TRUE.
   INTEGER :: N_VERTS_BASE, N_FACES_BASE, N_VOLUS_BASE
   INTEGER :: N_VERTS, N_EDGES, N_FACES, N_VOLUS, NSUB_GEOMS
   INTEGER :: GEOM_TYPE
   LOGICAL :: HAVE_SURF, HAVE_MATL
   CHARACTER(60) :: BNDC_FILENAME='null', GEOC_FILENAME='null' ! for compatibility with existing FDS code
   REAL(EB) :: OMEGA=0._EB                                     ! for compatibility with existing FDS code
   INTEGER, ALLOCATABLE, DIMENSION(:) :: FACES, VOLUS, SUB_GEOMS, SURFS, MATLS
   INTEGER, ALLOCATABLE, DIMENSION(:,:) :: EDGES, FACE_EDGES, EDGE_FACES
   REAL(EB),ALLOCATABLE, DIMENSION(:,:) :: FACES_NORMAL
   REAL(EB),ALLOCATABLE, DIMENSION(:) :: FACES_AREA
   REAL(EB) :: GEOM_VOLUME, GEOM_AREA
   REAL(EB) :: XYZ0(3)
   REAL(EB) :: AZIM_BASE, ELEV_BASE, SCALE_BASE(3), XYZ_BASE(3)
   REAL(EB) :: AZIM,      ELEV,      SCALE(3),      XYZ(3)
   REAL(EB) :: AZIM_DOT, ELEV_DOT, SCALE_DOT(3), XYZ_DOT(3)
   REAL(EB) :: GAXIS(3), GROTATE, GROTATE_DOT, GROTATE_BASE
   REAL(EB) :: XB(6)
   REAL(EB) :: SPHERE_ORIGIN(3), SPHERE_RADIUS
   INTEGER :: IJK(3), N_LEVELS
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: VERTS_BASE, VERTS, TFACES, DAZIM, DELEV, ZVALS
   REAL(EB), ALLOCATABLE, DIMENSION(:,:) :: DSCALE, DXYZ0, DXYZ

   CHARACTER(60) :: TEXTURE_MAPPING
   REAL(EB) :: TEXTURE_ORIGIN(3), TEXTURE_SCALE(2)
   LOGICAL :: AUTO_TEXTURE
END TYPE GEOMETRY_TYPE

INTEGER :: N_GEOMETRY=0, GEOMETRY_CHANGE_STATE=0
TYPE(GEOMETRY_TYPE), ALLOCATABLE, TARGET, DIMENSION(:) :: GEOMETRY
LOGICAL :: IS_GEOMETRY_DYNAMIC

TYPE VERTEX_TYPE
   REAL(EB) :: X,Y,Z
   REAL(EB) :: XYZ(3) ! this form may be more efficient
END TYPE VERTEX_TYPE

TYPE(VERTEX_TYPE), TARGET, ALLOCATABLE, DIMENSION(:) :: VERTEX

! --- CC_IBM types:
! Edge crossings data structure:
INTEGER, PARAMETER :: IBM_MAXCROSS_EDGE = 10 ! Size definition parameter. Max number of crossings per Cartesian Edge.
TYPE IBM_EDGECROSS_TYPE
   INTEGER :: NCROSS   ! Number of BODINT_PLANE segments - Cartesian edge crossings.
   REAL(EB), DIMENSION(1:IBM_MAXCROSS_EDGE)   ::  SVAR ! Locations along x2 axis of NCROSS intersections.
   INTEGER,  DIMENSION(1:IBM_MAXCROSS_EDGE)   :: ISVAR ! Type of intersection (i.e. SG, GS or GG).
   INTEGER,  DIMENSION(MAX_DIM+1)             ::   IJK ! [ i j k X2AXIS]
END TYPE IBM_EDGECROSS_TYPE

! Cartesian Edge Cut-Edges data structure:
INTEGER, PARAMETER :: IBM_MAXVERTS_EDGE  = 10 ! Size definition parameter. Max number of vertices per Cartesian Edge.
INTEGER, PARAMETER :: IBM_MAXCEELEM_EDGE = 10 ! Size definition parameter. Max number of cut edges per Cartesian Edge.
TYPE IBM_CUTEDGE_TYPE
   INTEGER :: NVERT, NEDGE, STATUS            ! Local Vertices, cut-edges and status of this Cartesian edge.
   REAL(EB), DIMENSION(IAXIS:KAXIS,1:IBM_MAXVERTS_EDGE)           :: XYZVERT  ! Locations of vertices.
   INTEGER,  DIMENSION(NOD1:NOD2,1:IBM_MAXCEELEM_EDGE)            ::  CEELEM  ! Cut-Edge connectivities.
   INTEGER,  DIMENSION(MAX_DIM+2)                                 ::     IJK  ! [ i j k X2AXIS cetype]
   INTEGER,  DIMENSION(IBM_MAX_WSTRIANG_SEG+2,IBM_MAXCEELEM_EDGE) ::  INDSEG  ! [ntr tr1 tr2 ibod]
END TYPE IBM_CUTEDGE_TYPE

! Cartesian Faces Cut-Faces data structure:
INTEGER, PARAMETER :: IBM_MAXVERTS_FACE  = 24 ! Size definition parameter. Max number of vertices per Cartesian Face.
INTEGER, PARAMETER :: IBM_MAXCEELEM_FACE = IBM_MAXVERTS_FACE ! Size definition parameter. Max segments per face.
INTEGER, PARAMETER :: IBM_MAXCFELEM_FACE = 10 ! Size definition parameter. Max number of cut faces per Cartesian Face.
INTEGER, PARAMETER :: IBM_MAXVERT_CUTFACE= 16 ! Size definition parameter.
TYPE IBM_CUTFACE_TYPE
   INTEGER :: NVERT, NFACE, STATUS            ! Local Vertices, cut-faces and status of this Cartesian face.
   REAL(EB), DIMENSION(IAXIS:KAXIS,1:IBM_MAXVERTS_FACE)           :: XYZVERT  ! Locations of vertices.
   INTEGER,  DIMENSION(IBM_MAXVERT_CUTFACE,IBM_MAXCFELEM_FACE)    ::  CFELEM  ! Cut-faces connectivities.
   INTEGER,  DIMENSION(MAX_DIM+1)                                 ::     IJK  ! [ i j k X1AXIS]
   REAL(EB), DIMENSION(IBM_MAXCFELEM_FACE)                        ::    AREA  ! Cut-faces areas.
   REAL(EB), DIMENSION(IAXIS:KAXIS,1:IBM_MAXCFELEM_FACE)          ::  XYZCEN  ! Cut-faces centroid locations.
   !Integrals to be used in cut-cell volume and centroid computations.
   REAL(EB), DIMENSION(IBM_MAXCFELEM_FACE)                        ::  INXAREA, INXSQAREA, JNYSQAREA, KNZSQAREA
   INTEGER,  DIMENSION(1:2,1:IBM_MAXCFELEM_FACE)                  ::  BODTRI
END TYPE IBM_CUTFACE_TYPE

! Cartesian Cells Cut-Cells data structure:
INTEGER, PARAMETER :: IBM_MAXCCELEM_CELL  =  8 ! Size definition parameter. Max number of cut-cell per cart cell.
INTEGER, PARAMETER :: IBM_MAXCFELEM_CELL  = 32 ! Size definition parameter. Max number of cut-faces per cart cell.
INTEGER, PARAMETER :: IBM_MAXVERTS_CELL   = 96
INTEGER, PARAMETER :: IBM_MAXCEELEM_CELL  = IBM_MAXVERTS_CELL
INTEGER, PARAMETER :: IBM_MAXCFACE_CUTCELL= 16 ! Size definition parameter.
INTEGER, PARAMETER :: IBM_NPARAM_CCFACE   =  5 ! [face_type side iaxis cei icf]

TYPE IBM_CUTCELL_TYPE
   INTEGER :: NCELL
   INTEGER, DIMENSION(1:IBM_MAXCFACE_CUTCELL+2,IBM_MAXCCELEM_CELL) ::    CCELEM ! Cut-cells faces connectivities in FACE_LIST.
   INTEGER, DIMENSION(1:IBM_NPARAM_CCFACE,1:IBM_MAXCFELEM_CELL)    :: FACE_LIST ! List of faces, cut-faces.
   REAL(EB), DIMENSION(IBM_MAXCCELEM_CELL)                         ::    VOLUME ! Cut-cell volumes.
   REAL(EB), DIMENSION(IAXIS:KAXIS,1:IBM_MAXCCELEM_CELL)           ::    XYZCEN ! Cut-cell centroid locaitons.
END TYPE IBM_CUTCELL_TYPE

! -----------------------------------------
! http://www.sdsc.edu/~tkaiser/f90.html#Linked lists
TYPE LINKED_LIST_TYPE
   INTEGER :: INDEX                           ! data
   TYPE(LINKED_LIST_TYPE), POINTER :: NEXT    ! pointer to the next element
END TYPE LINKED_LIST_TYPE

TYPE CUTCELL_LINKED_LIST_TYPE
   INTEGER :: INDEX                                   ! data
   TYPE(CUTCELL_LINKED_LIST_TYPE), POINTER :: NEXT    ! pointer to the next element
   REAL(EB) :: AREA                                   ! cutcell area for index
END TYPE CUTCELL_LINKED_LIST_TYPE

TYPE CUTCELL_TYPE
   REAL(EB) :: VOL,RHO,TMP,DIV,A(6),S,N(3)
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: ZZ
   ! identify each face with area contribution to current cutcell
   ! note: this must include the faces and areas of Cartesian cells
   TYPE(CUTCELL_LINKED_LIST_TYPE), POINTER :: CUTCELL_FACE_LIST
END TYPE CUTCELL_TYPE

TYPE FACET_TYPE
   INTEGER :: VERTEX(3)=0,SURF_INDEX=0,BOUNDARY_TYPE
   CHARACTER(LABEL_LENGTH) :: SURF_ID='null'
   REAL(EB) :: NVEC(3)=0._EB,AW,EW,KW,DN,RDN,RHO_F,U_TAU,Y_PLUS,TMP_F,TMP_G,QCONF,HEAT_TRANS_COEF,QRADIN,QRADOUT
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: RHODW,ZZ_F
   REAL(EB), ALLOCATABLE, DIMENSION(:,:) :: ILW
   TYPE(CUTCELL_LINKED_LIST_TYPE), POINTER :: CUTCELL_LIST
END TYPE FACET_TYPE

TYPE(FACET_TYPE), ALLOCATABLE, TARGET, DIMENSION(:) :: FACET

TYPE VOLUME_TYPE
   INTEGER :: VERTEX(4)=0
   CHARACTER(LABEL_LENGTH) :: MATL_ID='null'
END TYPE VOLUME_TYPE

TYPE(VOLUME_TYPE), ALLOCATABLE, TARGET, DIMENSION(:) :: VOLUME

TYPE CSVF_TYPE
    CHARACTER(256) :: CSVFILE,UVWFILE
END TYPE CSVF_TYPE

TYPE(CSVF_TYPE), ALLOCATABLE, DIMENSION(:) :: CSVFINFO

TYPE VENTS_TYPE
   INTEGER :: I1=-1,I2=-1,J1=-1,J2=-1,K1=-1,K2=-1,BOUNDARY_TYPE=0,IOR=0,SURF_INDEX=0,DEVC_INDEX=-1,CTRL_INDEX=-1, &
              COLOR_INDICATOR=99,TYPE_INDICATOR=0,ORDINAL=0,PRESSURE_RAMP_INDEX=0,TMP_EXTERIOR_RAMP_INDEX=0,NODE_INDEX=-1
   INTEGER, DIMENSION(3) :: RGB=-1
   REAL(EB) :: TRANSPARENCY = 1._EB
   REAL(EB), DIMENSION(3) :: TEXTURE=0._EB
   REAL(EB) :: X1=0._EB,X2=0._EB,Y1=0._EB,Y2=0._EB,Z1=0._EB,Z2=0._EB,FDS_AREA=0._EB, &
               X1_ORIG=0._EB,X2_ORIG=0._EB,Y1_ORIG=0._EB,Y2_ORIG=0._EB,Z1_ORIG=0._EB,Z2_ORIG=0._EB, &
               X0=-9.E6_EB,Y0=-9.E6_EB,Z0=-9.E6_EB,FIRE_SPREAD_RATE,UNDIVIDED_INPUT_AREA=0._EB,INPUT_AREA=0._EB,&
               TMP_EXTERIOR=-1000._EB,DYNAMIC_PRESSURE=0._EB,UVW(3)=-1.E12_EB,RADIUS=-1._EB
   LOGICAL :: ACTIVATED=.TRUE.,GHOST_CELLS_ONLY=.FALSE.,IS_WIND_BOUNDARY=.FALSE.
   CHARACTER(LABEL_LENGTH) :: DEVC_ID='null',CTRL_ID='null',ID='null'
   ! turbulent inflow (experimental)
   INTEGER :: N_EDDY=0
   REAL(EB) :: R_IJ(3,3)=0._EB,A_IJ(3,3),SIGMA_IJ(3,3),EDDY_BOX_VOLUME=0._EB, &
               X_EDDY_MIN=0._EB,X_EDDY_MAX=0._EB, &
               Y_EDDY_MIN=0._EB,Y_EDDY_MAX=0._EB, &
               Z_EDDY_MIN=0._EB,Z_EDDY_MAX=0._EB
   REAL(EB), ALLOCATABLE, DIMENSION(:,:) :: U_EDDY,V_EDDY,W_EDDY
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: X_EDDY,Y_EDDY,Z_EDDY,CU_EDDY,CV_EDDY,CW_EDDY
END TYPE VENTS_TYPE

TYPE TABLES_TYPE
   INTEGER :: NUMBER_ROWS,NUMBER_COLUMNS
   REAL(EB) :: LX,LY,UX,UY
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: X,Y
   REAL(EB), ALLOCATABLE, DIMENSION(:,:) :: TABLE_DATA,Z
END TYPE TABLES_TYPE

TYPE (TABLES_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: TABLES

TYPE RAMPS_TYPE
   REAL(EB) :: SPAN,RDT,T_MIN,T_MAX
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: INDEPENDENT_DATA,DEPENDENT_DATA,INTERPOLATED_DATA
   INTEGER :: NUMBER_DATA_POINTS,NUMBER_INTERPOLATION_POINTS,DEVC_INDEX=-1,CTRL_INDEX=-1
   CHARACTER(LABEL_LENGTH) :: DEVC_ID='null',CTRL_ID='null'
   LOGICAL :: DEP_VAR_UNITS_CONVERTED=.FALSE.,RESERVED=.FALSE.
END TYPE RAMPS_TYPE

TYPE (RAMPS_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: RAMPS

TYPE HUMAN_TYPE
   CHARACTER(60) :: NODE_NAME='null'
   CHARACTER(LABEL_LENGTH) :: FFIELD_NAME='null'
   REAL(EB) :: X=0._EB,Y=0._EB,Z=0._EB,U=0._EB,V=0._EB,W=0._EB,F_X=0._EB,F_Y=0._EB,&
               X_old=0._EB,Y_old=0._EB,X_group=0._EB,Y_group=0._EB, U_CB=0.0_EB, V_CB=0.0_EB
   REAL(EB) :: UBAR=0._EB, VBAR=0._EB, UBAR_Center=0._EB, VBAR_Center=0._EB, T_LastRead_CB=0.0_EB
   REAL(EB) :: Speed=1.25_EB, Radius=0.255_EB, Mass=80.0_EB, Tpre=1._EB, Tau=1._EB, &
               Eta=0._EB, Ksi=0._EB, Tdet=0._EB, Speed_ave=0._EB, T_Speed_ave=0._EB, &
               X_CB=0.0_EB, Y_CB=0.0_EB, X2_CB=0.0_EB, Y2_CB=0.0_EB, UAVE_CB=0.0_EB, VAVE_CB=0.0_EB
   REAL(EB) :: r_torso=0.15_EB, r_shoulder=0.095_EB, d_shoulder=0.055_EB, angle=0._EB, &
               torque=0._EB, m_iner=4._EB
   REAL(EB) :: tau_iner=0.2_EB, angle_old=0._EB, omega=0._EB
   REAL(EB) :: A=2000._EB, B=0.08_EB, C_Young=120000._EB, Gamma=16000._EB, Kappa=40000._EB, &
               Lambda=0.5_EB, Commitment=0._EB
   REAL(EB) :: SumForces=0._EB, IntDose=0._EB, DoseCrit1=0._EB, DoseCrit2=0._EB, SumForces2=0._EB
   REAL(EB) :: TempMax1=0._EB, FluxMax1=0._EB, TempMax2=0._EB, FluxMax2=0._EB, Density=0._EB, DensityR=0._EB, DensityL=0._EB
   REAL(EB) :: P_detect_tot=0._EB, v0_fac=1._EB, D_Walls=0._EB
   REAL(EB) :: T_FallenDown=0._EB, F_FallDown=0._EB, Angle_FallenDown=0._EB, SizeFac_FallenDown=0._EB, T_CheckFallDown=0._EB
   INTEGER  :: IOR=-1, ILABEL=0, COLOR_INDEX=0, INODE=0, IMESH=-1, IPC=0, IEL=0, I_FFIELD=0, I_Target2=0, ID_CB=-1
   INTEGER  :: GROUP_ID=0, DETECT1=0, GROUP_SIZE=0, I_Target=0, I_DoorAlgo=0, I_Door_Mode=0, STRS_Direction = 1
   REAL(EB) :: FX_Group=0._EB, FY_Group=0._EB
   REAL(EB) :: FX_Hazard=0._EB, FY_Hazard=0._EB
   INTEGER  :: NEW_ID=0
   INTEGER  :: STR_SUB_INDX, SKIP_WALL_FORCE_IOR
   LOGICAL  :: SHOW=.TRUE., NewRnd=.TRUE., CROWBAR_READ_IN=.FALSE., CROWBAR_UPDATE_V0=.FALSE.
   LOGICAL  :: SeeDoorXB1=.FALSE., SeeDoorXB2=.FALSE., SeeDoorXYZ1=.FALSE., SeeDoorXYZ2=.FALSE.
END TYPE HUMAN_TYPE

TYPE HUMAN_GRID_TYPE
! (x,y,z) Centers of the grid cells in the main evacuation meshes
! SOOT_DENS: Smoke density at the center of the cell (mg/m3)
! FED_CO_CO2_O2: Purser's FED for co, co2, and o2
   REAL(EB) :: X,Y,Z,SOOT_DENS,FED_CO_CO2_O2,TMP_G,RADFLUX
   INTEGER :: N, N_old, IGRID, IHUMAN, ILABEL
! IMESH: (x,y,z) which fire mesh, if any
! II,JJ,KK: Fire mesh cell reference
   INTEGER  :: IMESH,II,JJ,KK
END TYPE HUMAN_GRID_TYPE

TYPE SLICE_TYPE
   INTEGER :: I1,I2,J1,J2,K1,K2,INDEX,INDEX2=0,Z_INDEX=-999,Y_INDEX=-999,PART_INDEX=0,VELO_INDEX=0,PROP_INDEX=0,REAC_INDEX=0,IOR=0
   REAL(FB), DIMENSION(2) :: MINMAX
   REAL(EB):: SLICE_AGL
   LOGICAL :: TERRAIN_SLICE=.FALSE.,CELL_CENTERED=.FALSE., FIRE_LINE=.FALSE.,LEVEL_SET_FIRE_LINE=.FALSE.,FACE_CENTERED=.FALSE.
   CHARACTER(60) :: SLICETYPE='STRUCTURED',SMOKEVIEW_LABEL
   CHARACTER(LABEL_LENGTH) :: SMOKEVIEW_BAR_LABEL,ID='null'
END TYPE SLICE_TYPE

TYPE PATCH_TYPE
   INTEGER :: I1,I2,J1,J2,K1,K2,IG1,IG2,JG1,JG2,KG1,KG2,IOR,OBST_INDEX
END TYPE PATCH_TYPE

TYPE BOUNDARY_FILE_TYPE
   INTEGER :: INDEX,PROP_INDEX,Z_INDEX=-999,Y_INDEX=-999,PART_INDEX=0,TIME_INTEGRAL_INDEX=0
   CHARACTER(60) :: SMOKEVIEW_LABEL
   CHARACTER(LABEL_LENGTH) :: SMOKEVIEW_BAR_LABEL,UNITS
   LOGICAL :: CELL_CENTERED=.FALSE.
END TYPE BOUNDARY_FILE_TYPE

TYPE (BOUNDARY_FILE_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: BOUNDARY_FILE

TYPE BOUNDARY_ELEMENT_FILE_TYPE
   INTEGER :: INDEX,PROP_INDEX,Z_INDEX=-999,Y_INDEX=-999,PART_INDEX=0
   CHARACTER(60) :: SMOKEVIEW_LABEL
   CHARACTER(LABEL_LENGTH) :: SMOKEVIEW_BAR_LABEL
   LOGICAL :: CELL_CENTERED=.TRUE.
END TYPE BOUNDARY_ELEMENT_FILE_TYPE

TYPE (BOUNDARY_ELEMENT_FILE_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: BOUNDARY_ELEMENT_FILE

TYPE ISOSURFACE_FILE_TYPE
   INTEGER :: INDEX=1,N_VALUES=1,Y_INDEX=-999,Z_INDEX=-999,VELO_INDEX=0
   REAL(FB) :: VALUE(10)
   CHARACTER(60) :: SMOKEVIEW_LABEL
   CHARACTER(LABEL_LENGTH) :: SMOKEVIEW_BAR_LABEL
END TYPE ISOSURFACE_FILE_TYPE

TYPE (ISOSURFACE_FILE_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: ISOSURFACE_FILE

TYPE PROFILE_TYPE
   REAL(EB) :: X,Y,Z
   INTEGER  :: IOR,IW,ORDINAL,MESH,FORMAT_INDEX=1
   CHARACTER(LABEL_LENGTH) :: ID,QUANTITY
END TYPE PROFILE_TYPE

TYPE (PROFILE_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: PROFILE

TYPE INITIALIZATION_TYPE
   REAL(EB) :: TEMPERATURE,DENSITY,X1,X2,Y1,Y2,Z1,Z2,MASS_PER_VOLUME,MASS_PER_TIME,DT_INSERT, &
               X0,Y0,Z0,U0,V0,W0,VOLUME,HRRPUV=0._EB,DX=0._EB,DY=0._EB,DZ=0._EB,HEIGHT,RADIUS,DIAMETER=-1._EB, &
               PARTICLE_WEIGHT_FACTOR,AIT=1.E20_EB
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: PARTICLE_INSERT_CLOCK,MASS_FRACTION
   INTEGER  :: PART_INDEX=0,N_PARTICLES,LU_PARTICLE,PROF_INDEX=0,DEVC_INDEX=0,CTRL_INDEX=0,TABL_INDEX=0, &
               N_PARTICLES_PER_CELL=0
   LOGICAL :: ADJUST_DENSITY=.FALSE.,ADJUST_TEMPERATURE=.FALSE.,SINGLE_INSERTION=.TRUE., &
              CELL_CENTERED=.FALSE.
   LOGICAL, ALLOCATABLE, DIMENSION(:) :: ALREADY_INSERTED
   CHARACTER(LABEL_LENGTH) :: SHAPE,DEVC_ID,CTRL_ID,ID
END TYPE INITIALIZATION_TYPE

TYPE (INITIALIZATION_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: INITIALIZATION

TYPE INIT_RESERVED_TYPE
   REAL(EB) :: XYZ(3),DX,DY,DZ
   INTEGER :: N_PARTICLES,DEVC_INDEX
   CHARACTER(LABEL_LENGTH) :: DEVC_ID
END TYPE INIT_RESERVED_TYPE

TYPE (INIT_RESERVED_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: INIT_RESERVED

TYPE P_ZONE_TYPE
   REAL(EB) :: X1,X2,Y1,Y2,Z1,Z2,DPSTAR=0._EB
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: LEAK_AREA, LEAK_REFERENCE_PRESSURE, LEAK_PRESSURE_EXPONENT
   INTEGER :: N_DUCTNODES,MESH_INDEX=0
   LOGICAL :: EVACUATION=.FALSE.,PERIODIC=.FALSE.
   INTEGER, ALLOCATABLE, DIMENSION(:) :: NODE_INDEX
   CHARACTER(LABEL_LENGTH) :: ID
END TYPE P_ZONE_TYPE

TYPE (P_ZONE_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: P_ZONE

TYPE MULTIPLIER_TYPE
   REAL(EB) :: DXB(6),DX0,DY0,DZ0
   INTEGER  :: I_LOWER,I_UPPER,J_LOWER,J_UPPER,K_LOWER,K_UPPER,N_LOWER,N_UPPER,N_COPIES
   CHARACTER(LABEL_LENGTH) :: ID
   LOGICAL :: SEQUENTIAL=.FALSE.
END TYPE MULTIPLIER_TYPE

TYPE (MULTIPLIER_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: MULTIPLIER

TYPE FILTER_TYPE
   INTEGER :: RAMP_INDEX = -1
   CHARACTER(LABEL_LENGTH) :: ID,TABLE_ID
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: EFFICIENCY,MULTIPLIER
   REAL(EB) :: CLEAN_LOSS,LOADING_LOSS
END TYPE FILTER_TYPE

TYPE (FILTER_TYPE), DIMENSION(:), ALLOCATABLE,  TARGET :: FILTER

TYPE DUCTNODE_TYPE
   INTEGER :: FILTER_INDEX=-1, N_DUCTS,VENT_INDEX = -1, MESH_INDEX = -1,ZONE_INDEX=-1
   INTEGER, ALLOCATABLE, DIMENSION(:) :: DUCT_INDEX
   CHARACTER(LABEL_LENGTH) :: ID,TABLE_ID,VENT_ID='null'
   REAL(EB), ALLOCATABLE, DIMENSION(:,:) :: LOSS_ARRAY,FILTER_LOADING
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: ZZ,DIR,ZZ_V
   REAL(EB) :: LOSS, P,P_OLD,TMP,RHO,RSUM,CP,XYZ(3),FILTER_LOSS,TMP_V,RHO_V,RSUM_V,CP_V
   LOGICAL :: UPDATED, READ_IN, FIXED, AMBIENT = .FALSE.,LEAKAGE=.FALSE.,VENT=.FALSE.
   LOGICAL, ALLOCATABLE, DIMENSION(:) :: IN_MESH
END TYPE DUCTNODE_TYPE

TYPE (DUCTNODE_TYPE), DIMENSION(:), ALLOCATABLE,  TARGET :: DUCTNODE

TYPE NODE_BC_TYPE
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: ZZ_V
   REAL(EB) :: TMP_V,RHO_V,RSUM_V,CP_V, P
END TYPE NODE_BC_TYPE

TYPE DUCT_TYPE
   INTEGER :: NODE_INDEX(2)=-1,DEVC_INDEX=-1,CTRL_INDEX=-1,FAN_INDEX=-1,AIRCOIL_INDEX=-1,RAMP_INDEX=0,RAMP_LOSS_INDEX=0,&
              N_CELLS=1,DUCT_INTERP_TYPE_INDEX,SURF_INDEX=-1,LPC_INDEX=-1
   REAL(EB) :: AREA,AREA_INITIAL,COIL_Q=0._EB,CP_D,DIAMETER,DP_FAN(2)=0._EB,DX=-1._EB,LENGTH,MASS_FLOW_INITIAL=1.E6_EB,&
               RHO_D,ROUGHNESS,RSUM_D=0._EB,TAU=-1._EB,TMP_D,TOTAL_LOSS=0._EB,VEL(4)=0._EB,VOLUME_FLOW=1.E6_EB,LOSS(2)=0._EB,&
               VOLUME_FLOW_INITIAL=1.E6_EB
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: CP_C,RHO_C,TMP_C,ZZ,PART_INDEX,PART_CELL_INDEX
   REAL(EB), ALLOCATABLE, DIMENSION(:,:) :: ZZ_C
   LOGICAL :: ROUND = .TRUE.,SQUARE = .FALSE.,DAMPER = .FALSE.,DAMPER_OPEN = .TRUE.,FAN_OPERATING=.TRUE.,COIL_OPERATING=.TRUE.,&
              FIXED=.FALSE.,REVERSE=.FALSE.,UPDATED,LEAKAGE=.FALSE.,LEAK_ENTHALPY=.FALSE.
   CHARACTER(LABEL_LENGTH) :: ID
   REAL(EB) :: FAN_ON_TIME = 1.E10_EB,COIL_ON_TIME = 1.E10_EB
END TYPE DUCT_TYPE

TYPE (DUCT_TYPE), DIMENSION(:), ALLOCATABLE,  TARGET :: DUCT

TYPE FAN_TYPE
   INTEGER :: FAN_TYPE,RAMP_INDEX,SPIN_INDEX=0
   REAL(EB) :: VOL_FLOW,MAX_FLOW,MAX_PRES,OFF_LOSS=0._EB,TAU=0._EB
   CHARACTER(LABEL_LENGTH) :: ID,FAN_RAMP
END TYPE FAN_TYPE

TYPE(FAN_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: FAN

TYPE AIRCOIL_TYPE
   REAL(EB) :: COOLANT_TEMPERATURE=293.15_EB,COOLANT_SPECIFIC_HEAT=4186._EB, EFFICIENCY, COOLANT_MASS_FLOW=-9999._EB, &
               FIXED_Q=-1.E10_EB,TAU=0._EB
   INTEGER :: RAMP_INDEX=0
   CHARACTER(LABEL_LENGTH) :: ID
END TYPE AIRCOIL_TYPE

TYPE(AIRCOIL_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: AIRCOIL

TYPE NETWORK_TYPE
   INTEGER :: N_DUCTS,N_DUCTNODES,N_MATRIX
   INTEGER, ALLOCATABLE, DIMENSION(:) :: DUCT_INDEX,NODE_INDEX,MATRIX_INDEX
END TYPE NETWORK_TYPE

TYPE(NETWORK_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: NETWORK

TYPE DUCTRUN_TYPE
   INTEGER :: N_DUCTS,N_DUCTNODES,DUCT_INTERP_TYPE_INDEX
   INTEGER, ALLOCATABLE, DIMENSION(:) :: DUCT_INDEX,NODE_INDEX
END TYPE DUCTRUN_TYPE

TYPE(DUCTRUN_TYPE), DIMENSION(:), ALLOCATABLE, TARGET :: DUCTRUN


END MODULE TYPES


MODULE DEVICE_VARIABLES

USE PRECISION_PARAMETERS
IMPLICIT NONE

INTEGER, ALLOCATABLE, DIMENSION(:) :: DEVC_PIPE_OPERATING

TYPE PROPERTY_TYPE
   REAL(EB) :: DENSITY,DIAMETER,EMISSIVITY,HEAT_TRANSFER_COEFFICIENT,SPECIFIC_HEAT,RTI, &
               ACTIVATION_TEMPERATURE,ACTIVATION_OBSCURATION, &
               ALPHA_E,ALPHA_C,BETA_E,BETA_C,CHARACTERISTIC_VELOCITY,PARTICLE_VELOCITY,MASS_FLOW_RATE,FLOW_RATE,FLOW_TAU, &
               GAUGE_EMISSIVITY,GAUGE_TEMPERATURE,INITIAL_TEMPERATURE,K_FACTOR,C_FACTOR,OPERATING_PRESSURE,OFFSET,&
               SPRAY_ANGLE(2,2),P0=0._EB,PX(3)=0._EB,PXX(3,3)=0._EB
   INTEGER  :: PDPA_M=0,PDPA_N=0,N_SMOKEVIEW_PARAMETERS=0,N_SMOKEVIEW_IDS=0,N_INSERT,I_VEL=0,PARTICLES_PER_SECOND
   LOGICAL  :: PDPA_INTEGRATE=.TRUE.,PDPA_NORMALIZE=.TRUE.,PDPA_HISTOGRAM=.FALSE.,PDPA_HISTOGRAM_CUMULATIVE=.FALSE.
   REAL(EB) :: PDPA_START=0._EB,PDPA_END=1.E6_EB,PDPA_RADIUS=0.1_EB
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: TABLE_ROW, V_FACTOR
   INTEGER  :: PART_INDEX=-1,FLOW_RAMP_INDEX,SPRAY_PATTERN_INDEX,Z_INDEX=-999,Y_INDEX=-999,PRESSURE_RAMP_INDEX
   CHARACTER(LABEL_LENGTH) :: SMOKEVIEW_ID(SMOKEVIEW_OBJECTS_DIMENSION),PART_ID,ID,QUANTITY,TABLE_ID,SPEC_ID='null', &
                    SMOKEVIEW_PARAMETERS(SMOKEVIEW_OBJECTS_DIMENSION)='null'
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: SPRAY_LON_CDF,SPRAY_LON,SPRAY_LAT
   REAL(EB), ALLOCATABLE, DIMENSION(:,:) :: SPRAY_LAT_CDF
   REAL(EB) :: PDPA_HISTOGRAM_LIMITS(2) = 0._EB
   INTEGER :: PDPA_HISTOGRAM_NBINS=10,FED_ACTIVITY=2
END TYPE PROPERTY_TYPE


TYPE DEVICE_TYPE
   REAL(EB) :: T,X,Y,Z,X1,X2,Y1,Y2,Z1,Z2,INITIAL_VALUE=-1.E10_EB,INSTANT_VALUE,AVERAGE_VALUE=0._EB,AVERAGE_VALUE2=0._EB,&
               RMS_VALUE=0._EB,RMS_VALUE2=0._EB,COV_VALUE=0._EB,VALUE, &
               DEPTH,TMP_L,Y_C,OBSCURATION,DELAY,ROTATION,SMOOTHED_VALUE=-1.E10_EB,SMOOTHING_FACTOR=0._EB,&
               SETPOINT, T_CHANGE=1.E6_EB,BYPASS_FLOWRATE,DT,TOTAL_FLOWRATE,FLOWRATE,TI_T,TI_VALUE, &
               CONVERSION_FACTOR=1._EB, COORD_FACTOR=1._EB, &
               TIME_INTERVAL,TIME_MIN_VALUE=999._EB,TIME_MAX_VALUE=-999._EB,QUANTITY_RANGE(2),STATISTICS_START=-1.E20_EB
   REAL(EB) :: PDPA_NUMER=0._EB,PDPA_DENUM=0._EB
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: D_PATH,TIME_ARRAY
   REAL(EB), ALLOCATABLE, DIMENSION(:,:) :: YY_SOOT
   INTEGER  :: OUTPUT_INDEX,OUTPUT2_INDEX,IOR,IOR_ASSUMED=0,WALL_INDEX=-1,ORDINAL,I,J,K,MESH,I1=-1,I2=-1,J1=-1,J2=-1,K1=-1,K2=-1,&
               I_DEPTH,N_PATH,N_T_E,PROP_INDEX,ORIENTATION_INDEX=0,STATISTICS_LOCATION_INDEX=0,&
               TRIP_DIRECTION,CTRL_INDEX=-1,N_INPUTS,SURF_INDEX=-1,Z_INDEX=-999,Y_INDEX=-999,PART_INDEX=0,REAC_INDEX=0,&
               VELO_INDEX=0,NO_UPDATE_DEVC_INDEX=-1,NO_UPDATE_CTRL_INDEX=-1,FACE_INDEX=-1,FED_ACTIVITY=2
   INTEGER  :: DUCT_INDEX=-1,NODE_INDEX(2)=-1,POINT=1,LINE=0,LINE_COORD_CODE=123,PIPE_INDEX=1,LP_TAG=0,ORIENTATION_NUMBER=0, &
               DUCT_CELL_INDEX
   INTEGER, ALLOCATABLE, DIMENSION(:) :: DEVC_INDEX
   INTEGER, ALLOCATABLE, DIMENSION(:) :: I_PATH,J_PATH,K_PATH
   REAL(EB),  POINTER, DIMENSION(:) :: Y_E,T_E
   CHARACTER(LABEL_LENGTH) :: ID,PROP_ID,QUANTITY,QUANTITY2,CTRL_ID,DEVC_ID,STATISTICS='null',&
                    SURF_ID,PART_ID='null',SPEC_ID='null',MATL_ID='null',&
                    SMOKEVIEW_BAR_LABEL,UNITS='null',DUCT_ID='null',NODE_ID(2)='null',&
                    R_ID='null',X_ID='null',Y_ID='null',Z_ID='null',&
                    INIT_ID='null',NO_UPDATE_DEVC_ID='null',NO_UPDATE_CTRL_ID='null',REAC_ID='null'
   CHARACTER(60) :: SMOKEVIEW_LABEL
   LOGICAL :: INITIAL_STATE,CURRENT_STATE,LATCH,PRIOR_STATE,DRY=.FALSE.,TIME_AVERAGED=.TRUE., &
              EVACUATION=.FALSE.,RELATIVE=.FALSE.,OUTPUT=.TRUE.
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: PDPA_HISTOGRAM_COUNTS
END TYPE DEVICE_TYPE

! Device arrays

INTEGER :: N_PROP,N_DEVC,N_DEVC_TIME,N_DEVC_LINE,MAX_DEVC_LINE_POINTS=1,N_PDPA_HISTOGRAM = 0,MAX_PDPA_HISTOGRAM_NBINS = 0
CHARACTER(80), ALLOCATABLE, DIMENSION(:) :: TIME_DEVC_LABEL,TIME_DEVC_UNITS,LINE_DEVC_LABEL,LINE_DEVC_UNITS
CHARACTER(80), ALLOCATABLE, DIMENSION(:,:) :: LINE_DEVC_VALUE
REAL(EB), ALLOCATABLE, DIMENSION(:) :: TIME_DEVC_VALUE
TYPE (PROPERTY_TYPE),  DIMENSION(:), ALLOCATABLE, TARGET :: PROPERTY
TYPE (DEVICE_TYPE),  DIMENSION(:), ALLOCATABLE, TARGET :: DEVICE

END MODULE DEVICE_VARIABLES


MODULE CONTROL_VARIABLES

! Variables for evaluating control functions

USE PRECISION_PARAMETERS

IMPLICIT NONE

TYPE CONTROL_TYPE
   LOGICAL :: SPECIFIED_STATE=.FALSE.,INITIAL_STATE=.FALSE.,CURRENT_STATE=.FALSE.,PRIOR_STATE=.FALSE.,LATCH=.TRUE.,UPDATED=.FALSE.
   LOGICAL :: EVACUATION=.FALSE.
   INTEGER :: CONTROL_INDEX=0,CYCLES=1,N_INPUTS=0,RAMP_INDEX=0,MESH=1,N=1,ON_BOUND=0,TRIP_DIRECTION
   INTEGER, ALLOCATABLE, DIMENSION (:) :: INPUT,INPUT_TYPE
   REAL(EB) :: SETPOINT(2)=1.E30_EB, DELAY=0._EB, T_CHANGE=1000000._EB ,CYCLE_TIME=1000000._EB,CONSTANT=-9.E30_EB,&
               INSTANT_VALUE,PROPORTIONAL_GAIN,INTEGRAL_GAIN,DIFFERENTIAL_GAIN,PREVIOUS_VALUE=-9.E30_EB,INTEGRAL=0._EB,&
               TARGET_VALUE = -9.E30_EB
   CHARACTER(LABEL_LENGTH) :: ID='null',RAMP_ID='null',INPUT_ID(40)='null'
END TYPE CONTROL_TYPE

TYPE (CONTROL_TYPE),  DIMENSION(:), ALLOCATABLE, TARGET :: CONTROL

INTEGER, PARAMETER :: AND_GATE=1, OR_GATE=2, XOR_GATE=3, X_OF_N_GATE=4, TIME_DELAY=5, DEADBAND=6, CYCLING=7, &
                      CUSTOM=8,KILL=9,CORE_DUMP=10,CF_SUM=11,CF_SUBTRACT=12,CF_MULTIPLY=13,CF_DIVIDE=14,CF_POWER=15,CF_PID=16,&
                      CF_EXP=17,CF_LOG=18,CF_SIN=19,CF_COS=20,CF_ASIN=21,CF_ACOS=22,DEVICE_INPUT=1,CONTROL_INPUT=2,CONSTANT_INPUT=3

INTEGER :: N_CTRL = 0, N_CTRL_FILES = 0

END MODULE CONTROL_VARIABLES


MODULE MESH_VARIABLES

! Data structure for mesh-dependent variables

USE PRECISION_PARAMETERS
USE TYPES
IMPLICIT NONE

TYPE MESH_TYPE

   REAL(EB), ALLOCATABLE, DIMENSION(:,:,:) :: &
            U,V,W,US,VS,WS,DDDT,D,DS,H,HS,H_PRIME,KRES,FVX,FVY,FVZ,FVX_B,FVY_B,FVZ_B,RHO,RHOS, &
            MU,MU_DNS,TMP,Q,FRHO,KAPPA,CHI_R,QR,QR_W,UII,RSUM,D_SOURCE,D_GEOMETRY, &
            CSD2,CHEM_SUBIT,MIX_TIME,STRAIN_RATE,D_Z_MAX,ZETA_SOURCE_TERM,AIT

   REAL(EB), ALLOCATABLE, DIMENSION(:,:,:,:) :: ZZ,ZZS,REAC_SOURCE_TERM,DEL_RHO_D_DEL_Z,FX,FY,FZ, &
                                                SCALAR_WORK1,SCALAR_WORK2,SCALAR_WORK3,SCALAR_WORK4, &
                                                Q_REAC
   REAL(EB), ALLOCATABLE, DIMENSION(:,:,:,:) :: AVG_DROP_DEN,AVG_DROP_TMP,AVG_DROP_RAD,AVG_DROP_AREA,M_DOT_PPP
   REAL(EB), ALLOCATABLE, DIMENSION(:,:,:) :: AVG_DROP_DEN_ALL
   REAL(EB), ALLOCATABLE, DIMENSION(:,:) :: UVW_GHOST

   REAL(EB) :: POIS_PTB,POIS_ERR,LAPLACE_PTB,LAPLACE_ERR
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: SAVE1,SAVE2,WORK
   REAL(EB), ALLOCATABLE, DIMENSION(:,:,:) :: PRHS
   REAL(EB), ALLOCATABLE, DIMENSION(:,:) :: BXS,BXF,BYS,BYF,BZS,BZF, BXST,BXFT,BYST,BYFT,BZST,BZFT
   INTEGER :: LSAVE,LWORK,LBC,MBC,NBC,LBC2,MBC2,NBC2,ITRN,JTRN,KTRN,IPS
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: P_0,RHO_0,TMP_0,D_PBAR_DT,D_PBAR_DT_S,U_LEAK,U_DUCT
   REAL(EB), ALLOCATABLE, DIMENSION(:,:) :: PBAR,PBAR_S,R_PBAR
   INTEGER, ALLOCATABLE, DIMENSION(:,:,:) :: PRESSURE_ZONE
   REAL(EB), ALLOCATABLE, DIMENSION(:,:,:) :: WORK1,WORK2,WORK3,WORK4,WORK5,WORK6,WORK7,WORK8,WORK9
   INTEGER, ALLOCATABLE, DIMENSION(:,:,:) :: IWORK1

   !! Laplace solve, sparse LU

   !INTEGER :: A_N_ROWS,A_N_COLS,A_N_ELEMENTS
   !INTEGER, ALLOCATABLE, DIMENSION(:) :: A_ROW_INDEX,A_COLUMNS
   !REAL(EB), ALLOCATABLE, DIMENSION(:) :: A_VALUES

   REAL(EB),     ALLOCATABLE, DIMENSION(:,:,:) :: PWORK1,PWORK2,PWORK3,PWORK4
   COMPLEX(DPC), ALLOCATABLE, DIMENSION(:,:,:) :: PWORK5,PWORK6,PWORK7,PWORK8

   REAL(EB), ALLOCATABLE, DIMENSION(:,:,:) :: TURB_WORK1,TURB_WORK2,TURB_WORK3,TURB_WORK4
   REAL(EB), ALLOCATABLE, DIMENSION(:,:,:) :: TURB_WORK5,TURB_WORK6,TURB_WORK7,TURB_WORK8
   REAL(EB), ALLOCATABLE, DIMENSION(:,:,:) :: TURB_WORK9,TURB_WORK10

   REAL(EB), ALLOCATABLE, DIMENSION(:,:,:) :: IBM_SAVE1,IBM_SAVE2,IBM_SAVE3,IBM_SAVE4,IBM_SAVE5,IBM_SAVE6
   INTEGER, ALLOCATABLE, DIMENSION(:,:,:) :: U_MASK,V_MASK,W_MASK,P_MASK

   REAL(EB), ALLOCATABLE, DIMENSION(:) :: WALL_WORK1,WALL_WORK2
   REAL(FB), ALLOCATABLE, DIMENSION(:,:,:,:) :: QQ
   REAL(FB), ALLOCATABLE, DIMENSION(:,:) :: PP,PPN,BNDF_TIME_INTEGRAL
   INTEGER, ALLOCATABLE, DIMENSION(:,:) :: IBK
   INTEGER, ALLOCATABLE, DIMENSION(:,:,:) :: IBLK

   REAL(EB) :: CFL,DIVMX,DIVMN,VN,RESMAX,PART_UVWMAX,DRAG_CFL
   INTEGER  :: ICFL,JCFL,KCFL,IMX,JMX,KMX,IMN,JMN,KMN, I_VN,J_VN,K_VN,IRM,JRM,KRM
   INTEGER  :: IUVW=1

   INTEGER :: N_EDGES
   INTEGER, ALLOCATABLE, DIMENSION(:,:) :: IJKE,EDGE_INDEX
   REAL(EB), ALLOCATABLE, DIMENSION(:,:) :: TAU_E,OME_E

   INTEGER :: MESH_LEVEL,LBC_EMB,MBC_EMB,NBC_EMB
   INTEGER :: IBAR,JBAR,KBAR,IBM1,JBM1,KBM1,IBP1,JBP1,KBP1
   INTEGER :: N_NEIGHBORING_MESHES
   INTEGER, ALLOCATABLE, DIMENSION(:) :: NEIGHBORING_MESH
   INTEGER, ALLOCATABLE, DIMENSION(:) :: RGB
   REAL(EB) :: DXI,DETA,DZETA,RDXI,RDETA,RDZETA, &
      DXMIN,DXMAX,DYMIN,DYMAX,DZMIN,DZMAX, &
      XS,XF,YS,YF,ZS,ZF,RDXINT,RDYINT,RDZINT,CELL_SIZE
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: R,RC,X,Y,Z,XC,YC,ZC,HX,HY,HZ, &
            DX,RDX,DXN,RDXN,DY,RDY,DYN,RDYN,DZ,RDZ,DZN,RDZN, &
            CELLSI,CELLSJ,CELLSK,RRN
   REAL(FB), ALLOCATABLE, DIMENSION(:) :: XPLT,YPLT,ZPLT

   INTEGER :: N_OBST
   TYPE(OBSTRUCTION_TYPE), ALLOCATABLE, DIMENSION(:) :: OBSTRUCTION

   INTEGER :: N_VENT
   TYPE(VENTS_TYPE), ALLOCATABLE, DIMENSION(:) :: VENTS

   INTEGER, ALLOCATABLE, DIMENSION(:,:,:) :: CELL_INDEX,CUTCELL_INDEX
   INTEGER, ALLOCATABLE, DIMENSION(:) :: I_CELL,J_CELL,K_CELL,OBST_INDEX_C
   INTEGER, ALLOCATABLE, DIMENSION(:) :: I_CUTCELL,J_CUTCELL,K_CUTCELL
   TYPE(CUTCELL_TYPE), ALLOCATABLE, DIMENSION(:) :: CUTCELL
   INTEGER, ALLOCATABLE, DIMENSION(:,:) :: WALL_INDEX
   LOGICAL, ALLOCATABLE, DIMENSION(:) :: SOLID,EXTERIOR,CONNECTED_MESH
   LOGICAL, ALLOCATABLE, DIMENSION(:,:,:) :: MEAN_FORCING_CELL

   INTEGER :: N_CUTCELLS=0 ! for debugging/visualization
   INTEGER, ALLOCATABLE, DIMENSION(:) :: CUTCELL_LIST ! for debugging/visualization

   !---------------------- STR: CC_IBM mesh Arrays ------------------------------------------
   INTEGER :: IBM_NEDGECROSS_MESH=0, IBM_NCUTEDGE_MESH=0, IBM_NCUTFACE_MESH=0, IBM_NCUTCELL_MESH=0
   INTEGER, ALLOCATABLE, DIMENSION(:,:,:,:) :: VERTVAR, CCVAR
   INTEGER, ALLOCATABLE, DIMENSION(:,:,:,:,:) :: ECVAR, FCVAR
   INTEGER ::  IBM_MAX_NEDGECROSS_MESH=0, IBM_MAX_NCUTEDGE_MESH=0, &
               IBM_MAX_NCUTFACE_MESH=0,   IBM_MAX_NCUTCELL_MESH=0
   TYPE(IBM_EDGECROSS_TYPE), ALLOCATABLE, DIMENSION(:) :: IBM_EDGECROSS
   TYPE(IBM_CUTEDGE_TYPE),   ALLOCATABLE, DIMENSION(:) :: IBM_CUT_EDGE
   TYPE(IBM_CUTFACE_TYPE),   ALLOCATABLE, DIMENSION(:) :: IBM_CUT_FACE
   TYPE(IBM_CUTCELL_TYPE),   ALLOCATABLE, DIMENSION(:) :: IBM_CUT_CELL
   !---------------------- END: CC_IBM mesh Arrays ------------------------------------------

   INTEGER :: N_WALL_CELLS,N_WALL_CELLS_DIM,N_INTERNAL_WALL_CELLS,N_EXTERNAL_WALL_CELLS,WALL_COUNTER
   REAL(EB) :: BC_CLOCK
   REAL(EB), ALLOCATABLE, DIMENSION(:,:) :: EDGE_INTERPOLATION_FACTOR
   REAL(EB), ALLOCATABLE, DIMENSION(:)   :: D_CORR,DS_CORR,UVW_SAVE,U_GHOST,V_GHOST,W_GHOST
   TYPE(WALL_TYPE), ALLOCATABLE, DIMENSION(:) :: WALL
   TYPE(EXTERNAL_WALL_TYPE), ALLOCATABLE, DIMENSION(:) :: EXTERNAL_WALL
   TYPE(OMESH_TYPE), ALLOCATABLE, DIMENSION(:) :: OMESH
   TYPE(LAGRANGIAN_PARTICLE_TYPE), ALLOCATABLE, DIMENSION(:) :: LAGRANGIAN_PARTICLE
   TYPE(STORAGE_TYPE), ALLOCATABLE, DIMENSION(:) :: PARTICLE_STORAGE,WALL_STORAGE
   INTEGER :: NLP,NLPDIM
   TYPE(HUMAN_TYPE), ALLOCATABLE, DIMENSION(:) :: HUMAN
   INTEGER :: N_HUMANS,N_HUMANS_DIM
   TYPE(HUMAN_GRID_TYPE), ALLOCATABLE, DIMENSION(:,:) :: HUMAN_GRID

   INTEGER :: N_SLCF
   TYPE(SLICE_TYPE), ALLOCATABLE, DIMENSION(:) :: SLICE

   INTEGER, ALLOCATABLE, DIMENSION(:,:) :: INC
   INTEGER :: N_PATCH
   TYPE(PATCH_TYPE), ALLOCATABLE, DIMENSION(:) :: PATCH

   REAL(EB), ALLOCATABLE, DIMENSION(:,:,:,:) :: UIID
   INTEGER :: RAD_CALL_COUNTER,ANGLE_INC_COUNTER

   INTEGER, ALLOCATABLE, DIMENSION(:,:,:) :: INTERPOLATED_MESH

   CHARACTER(80), ALLOCATABLE, DIMENSION(:) :: STRING
   INTEGER :: N_STRINGS,N_STRINGS_MAX

!rm ->
!  REAL(EB), ALLOCATABLE, DIMENSION(:,:,:,:) :: DMPVDT_FM_VEG
   INTEGER, ALLOCATABLE, DIMENSION(:,:,:) :: K_AGL_SLICE
   REAL(EB),ALLOCATABLE, DIMENSION(:,:) :: LS_Z_TERRAIN,VEG_DRAG
   INTEGER :: N_TERRAIN_SLCF
   REAL(EB) :: VEG_CLOCK_BC !surf veg
!rm <-

   ! Embedded Mesh

   REAL(EB), ALLOCATABLE, DIMENSION(:,:,:,:) :: SCALAR_SAVE1,SCALAR_SAVE2,SCALAR_SAVE3

END TYPE MESH_TYPE

TYPE (MESH_TYPE), SAVE, DIMENSION(:), ALLOCATABLE, TARGET :: MESHES

END MODULE MESH_VARIABLES


MODULE MESH_POINTERS

USE PRECISION_PARAMETERS
USE MESH_VARIABLES
IMPLICIT NONE

REAL(EB), POINTER, DIMENSION(:,:,:) :: &
   U,V,W,US,VS,WS,DDDT,D,DS,H,HS,H_PRIME,KRES,FVX,FVY,FVZ,FVX_B,FVY_B,FVZ_B,RHO,RHOS, &
   MU,MU_DNS,TMP,Q,FRHO,KAPPA,CHI_R,QR,QR_W,UII,RSUM,D_SOURCE,D_GEOMETRY, &
   CSD2,MTR,MSR,WEM,MIX_TIME,CHEM_SUBIT,STRAIN_RATE,D_Z_MAX,ZETA_SOURCE_TERM,AIT
REAL(EB), POINTER, DIMENSION(:,:,:,:) :: ZZ,ZZS,REAC_SOURCE_TERM,DEL_RHO_D_DEL_Z,FX,FY,FZ, &
                                         SCALAR_WORK1,SCALAR_WORK2,SCALAR_WORK3,SCALAR_WORK4, &
                                         Q_REAC
REAL(EB), POINTER, DIMENSION(:,:,:,:) :: AVG_DROP_DEN,AVG_DROP_TMP,AVG_DROP_RAD,AVG_DROP_AREA,M_DOT_PPP
REAL(EB), POINTER, DIMENSION(:,:,:)   :: AVG_DROP_DEN_ALL
REAL(EB), POINTER, DIMENSION(:,:) :: UVW_GHOST
REAL(EB), POINTER :: POIS_PTB,POIS_ERR,LAPLACE_PTB,LAPLACE_ERR
REAL(EB), POINTER, DIMENSION(:) :: SAVE1,SAVE2,WORK
REAL(EB), POINTER, DIMENSION(:,:,:) :: PRHS
REAL(EB), POINTER, DIMENSION(:,:) :: BXS,BXF,BYS,BYF,BZS,BZF, BXST,BXFT,BYST,BYFT,BZST,BZFT
INTEGER, POINTER :: LSAVE,LWORK,LBC,MBC,NBC,LBC2,MBC2,NBC2,ITRN,JTRN,KTRN,IPS
REAL(EB), POINTER, DIMENSION(:) :: P_0,RHO_0,TMP_0,D_PBAR_DT,D_PBAR_DT_S,U_LEAK,U_DUCT
REAL(EB), POINTER, DIMENSION(:,:) :: PBAR,PBAR_S,R_PBAR
INTEGER, POINTER, DIMENSION(:,:,:) :: PRESSURE_ZONE
REAL(EB), POINTER, DIMENSION(:,:,:) :: WORK1,WORK2,WORK3,WORK4,WORK5,WORK6,WORK7,WORK8,WORK9
INTEGER, POINTER, DIMENSION(:,:,:) :: IWORK1

!! Laplace solve, sparse LU
!
!INTEGER, POINTER :: A_N_ROWS,A_N_COLS,A_N_ELEMENTS
!INTEGER, POINTER, DIMENSION(:) :: A_ROW_INDEX,A_COLUMNS
!REAL(EB), POINTER, DIMENSION(:) :: A_VALUES

REAL(EB),     POINTER, DIMENSION(:,:,:) :: PWORK1,PWORK2,PWORK3,PWORK4
COMPLEX(DPC), POINTER, DIMENSION(:,:,:) :: PWORK5,PWORK6,PWORK7,PWORK8

REAL(EB), POINTER, DIMENSION(:,:,:) :: TURB_WORK1,TURB_WORK2,TURB_WORK3,TURB_WORK4
REAL(EB), POINTER, DIMENSION(:,:,:) :: TURB_WORK5,TURB_WORK6,TURB_WORK7,TURB_WORK8
REAL(EB), POINTER, DIMENSION(:,:,:) :: TURB_WORK9,TURB_WORK10

REAL(EB), POINTER, DIMENSION(:,:,:) :: IBM_SAVE1,IBM_SAVE2,IBM_SAVE3,IBM_SAVE4,IBM_SAVE5,IBM_SAVE6
INTEGER, POINTER, DIMENSION(:,:,:) :: U_MASK,V_MASK,W_MASK,P_MASK

REAL(EB), POINTER, DIMENSION(:) :: WALL_WORK1,WALL_WORK2
REAL(FB), POINTER, DIMENSION(:,:,:,:) :: QQ
REAL(FB), POINTER, DIMENSION(:,:) :: PP,PPN,BNDF_TIME_INTEGRAL
INTEGER, POINTER, DIMENSION(:,:) :: IBK
INTEGER, POINTER, DIMENSION(:,:,:) :: IBLK
REAL(EB), POINTER :: CFL,DIVMX,DIVMN,VN,RESMAX,PART_UVWMAX,DRAG_CFL
INTEGER, POINTER :: ICFL,JCFL,KCFL,IMX,JMX,KMX,IMN,JMN,KMN,I_VN,J_VN,K_VN,IRM,JRM,KRM,IUVW
INTEGER, POINTER :: N_EDGES
INTEGER, POINTER, DIMENSION(:,:) :: IJKE,EDGE_INDEX
REAL(EB), POINTER, DIMENSION(:,:) :: TAU_E,OME_E

INTEGER, POINTER :: MESH_LEVEL,LBC_EMB,MBC_EMB,NBC_EMB
INTEGER, POINTER :: IBAR,JBAR,KBAR,IBM1,JBM1,KBM1,IBP1,JBP1,KBP1
INTEGER, POINTER :: N_NEIGHBORING_MESHES
INTEGER, POINTER, DIMENSION(:) :: NEIGHBORING_MESH

INTEGER, POINTER, DIMENSION(:) :: RGB
REAL(EB), POINTER :: DXI,DETA,DZETA,RDXI,RDETA,RDZETA, &
   DXMIN,DXMAX,DYMIN,DYMAX,DZMIN,DZMAX, &
   XS,XF,YS,YF,ZS,ZF,RDXINT,RDYINT,RDZINT,CELL_SIZE
REAL(EB), POINTER, DIMENSION(:) :: R,RC,X,Y,Z,XC,YC,ZC,HX,HY,HZ, &
   DX,RDX,DXN,RDXN,DY,RDY,DYN,RDYN,DZ,RDZ,DZN,RDZN, &
   CELLSI,CELLSJ,CELLSK,RRN
REAL(FB), POINTER, DIMENSION(:) :: XPLT,YPLT,ZPLT
INTEGER, POINTER :: N_OBST
TYPE(OBSTRUCTION_TYPE), POINTER, DIMENSION(:) :: OBSTRUCTION
INTEGER, POINTER :: N_VENT
TYPE(VENTS_TYPE), POINTER, DIMENSION(:) :: VENTS
INTEGER, POINTER, DIMENSION(:,:,:) :: CELL_INDEX,CUTCELL_INDEX
INTEGER, POINTER, DIMENSION(:) :: I_CELL,J_CELL,K_CELL,OBST_INDEX_C,I_CUTCELL,J_CUTCELL,K_CUTCELL
INTEGER, POINTER, DIMENSION(:,:,:,:,:) :: FCVAR
TYPE(IBM_CUTFACE_TYPE),   POINTER, DIMENSION(:) :: IBM_CUT_FACE
TYPE(CUTCELL_TYPE), POINTER, DIMENSION(:) :: CUTCELL
INTEGER, POINTER, DIMENSION(:,:) :: WALL_INDEX
LOGICAL, POINTER, DIMENSION(:) :: SOLID,EXTERIOR,CONNECTED_MESH
LOGICAL, POINTER, DIMENSION(:,:,:) :: MEAN_FORCING_CELL
INTEGER, POINTER :: N_WALL_CELLS,N_WALL_CELLS_DIM,N_INTERNAL_WALL_CELLS,N_EXTERNAL_WALL_CELLS,WALL_COUNTER
REAL(EB),POINTER :: BC_CLOCK
REAL(EB), POINTER, DIMENSION(:,:) :: EDGE_INTERPOLATION_FACTOR
REAL(EB), POINTER, DIMENSION(:)   :: D_CORR,DS_CORR,UVW_SAVE,U_GHOST,V_GHOST,W_GHOST
TYPE(WALL_TYPE), POINTER, DIMENSION(:) :: WALL
TYPE(EXTERNAL_WALL_TYPE), POINTER, DIMENSION(:) :: EXTERNAL_WALL
TYPE(OMESH_TYPE), POINTER, DIMENSION(:) :: OMESH
TYPE(LAGRANGIAN_PARTICLE_TYPE), POINTER, DIMENSION(:) :: LAGRANGIAN_PARTICLE
TYPE(STORAGE_TYPE), POINTER, DIMENSION(:) :: WALL_STORAGE,PARTICLE_STORAGE
INTEGER, POINTER :: NLP,NLPDIM
TYPE(HUMAN_TYPE), POINTER, DIMENSION(:) :: HUMAN
INTEGER, POINTER :: N_HUMANS,N_HUMANS_DIM
TYPE(HUMAN_GRID_TYPE), POINTER, DIMENSION(:,:) :: HUMAN_GRID
INTEGER, POINTER :: N_SLCF
TYPE(SLICE_TYPE), POINTER, DIMENSION(:) :: SLICE
INTEGER, POINTER, DIMENSION(:,:) :: INC
INTEGER, POINTER :: N_PATCH
TYPE(PATCH_TYPE), POINTER, DIMENSION(:) :: PATCH
REAL(EB), POINTER, DIMENSION(:,:,:,:) :: UIID
INTEGER,  POINTER :: RAD_CALL_COUNTER,ANGLE_INC_COUNTER
INTEGER, POINTER, DIMENSION(:,:,:) :: INTERPOLATED_MESH
CHARACTER(80), POINTER, DIMENSION(:) :: STRING
INTEGER, POINTER :: N_STRINGS,N_STRINGS_MAX
!rm ->
!REAL(EB), POINTER, DIMENSION(:,:,:,:) :: DMPVDT_FM_VEG
INTEGER, POINTER, DIMENSION(:,:,:) :: K_AGL_SLICE
REAL(EB), POINTER,DIMENSION(:,:) :: LS_Z_TERRAIN,VEG_DRAG
INTEGER, POINTER :: N_TERRAIN_SLCF
REAL(EB), POINTER :: VEG_CLOCK_BC  !surf veg
!rm <-

! Embedded Mesh

REAL(EB), POINTER, DIMENSION(:,:,:,:) :: SCALAR_SAVE1,SCALAR_SAVE2,SCALAR_SAVE3


CONTAINS


SUBROUTINE POINT_TO_MESH(NM)

! Local names for MESH variables point to Global names

INTEGER, INTENT(IN) ::  NM
TYPE (MESH_TYPE), POINTER :: M

M=>MESHES(NM)
U=>M%U
V=>M%V
W=>M%W
US=>M%US
VS=>M%VS
WS=>M%WS
DDDT=>M%DDDT
D=>M%D
DS=>M%DS
H=>M%H
HS=>M%HS
H_PRIME=>M%H_PRIME
KRES=>M%KRES
FVX=>M%FVX
FVY=>M%FVY
FVZ=>M%FVZ
FVX_B=>M%FVX_B
FVY_B=>M%FVY_B
FVZ_B=>M%FVZ_B
RHO=>M%RHO
RHOS=>M%RHOS
TMP=>M%TMP
CHEM_SUBIT=>M%CHEM_SUBIT
FRHO=>M%FRHO
MU=>M%MU
MU_DNS=>M%MU_DNS
D_Z_MAX=>M%D_Z_MAX
CSD2=>M%CSD2
STRAIN_RATE=>M%STRAIN_RATE
MIX_TIME=>M%MIX_TIME
Q=>M%Q
Q_REAC=>M%Q_REAC
CHI_R => M%CHI_R
AIT=>M%AIT
QR=>M%QR
QR_W=>M%QR_W
KAPPA=>M%KAPPA
UII=>M%UII
M_DOT_PPP=>M%M_DOT_PPP
AVG_DROP_DEN=>M%AVG_DROP_DEN
AVG_DROP_AREA=>M%AVG_DROP_AREA
AVG_DROP_TMP=>M%AVG_DROP_TMP
AVG_DROP_RAD=>M%AVG_DROP_RAD
AVG_DROP_DEN_ALL=>M%AVG_DROP_DEN_ALL
D_SOURCE=>M%D_SOURCE
D_GEOMETRY=>M%D_GEOMETRY
RSUM=>M%RSUM
ZZ=>M%ZZ
ZZS=>M%ZZS
REAC_SOURCE_TERM=>M%REAC_SOURCE_TERM
ZETA_SOURCE_TERM=>M%ZETA_SOURCE_TERM
DEL_RHO_D_DEL_Z=>M%DEL_RHO_D_DEL_Z
FX=>M%FX
FY=>M%FY
FZ=>M%FZ
UVW_GHOST=>M%UVW_GHOST
POIS_PTB=>M%POIS_PTB
POIS_ERR=>M%POIS_ERR
LAPLACE_PTB=>M%LAPLACE_PTB
LAPLACE_ERR=>M%LAPLACE_ERR
SAVE1=>M%SAVE1
SAVE2=>M%SAVE2
!! Laplace solve
!A_N_ROWS=>M%A_N_ROWS
!A_N_COLS=>M%A_N_COLS
!A_N_ELEMENTS=>M%A_N_ELEMENTS
!A_ROW_INDEX=>M%A_ROW_INDEX
!A_COLUMNS=>M%A_COLUMNS
!A_VALUES=>M%A_VALUES
!! -------------
SCALAR_SAVE1=>M%SCALAR_SAVE1
SCALAR_SAVE2=>M%SCALAR_SAVE2
SCALAR_SAVE3=>M%SCALAR_SAVE3
SCALAR_WORK1=>M%SCALAR_WORK1
SCALAR_WORK2=>M%SCALAR_WORK2
SCALAR_WORK3=>M%SCALAR_WORK3
SCALAR_WORK4=>M%SCALAR_WORK4
WORK=>M%WORK
LSAVE=>M%LSAVE
LWORK=>M%LWORK
PRHS=>M%PRHS
BXS=>M%BXS
BXF=>M%BXF
BYS=>M%BYS
BYF=>M%BYF
BZS=>M%BZS
BZF=>M%BZF
BXST=>M%BXST
BXFT=>M%BXFT
BYST=>M%BYST
BYFT=>M%BYFT
BZST=>M%BZST
BZFT=>M%BZFT
LBC=>M%LBC
MBC=>M%MBC
NBC=>M%NBC
LBC2=>M%LBC2
MBC2=>M%MBC2
NBC2=>M%NBC2
ITRN=>M%ITRN
JTRN=>M%JTRN
KTRN=>M%KTRN
IPS=>M%IPS
LBC_EMB=>M%LBC_EMB
MBC_EMB=>M%MBC_EMB
NBC_EMB=>M%NBC_EMB
U_LEAK=>M%U_LEAK
U_DUCT=>M%U_DUCT
D_PBAR_DT=>M%D_PBAR_DT
D_PBAR_DT_S=>M%D_PBAR_DT_S
PBAR=>M%PBAR
PBAR_S=>M%PBAR_S
R_PBAR=>M%R_PBAR
P_0=>M%P_0
RHO_0=>M%RHO_0
TMP_0=>M%TMP_0
PRESSURE_ZONE=>M%PRESSURE_ZONE
WORK1=>M%WORK1
WORK2=>M%WORK2
WORK3=>M%WORK3
WORK4=>M%WORK4
WORK5=>M%WORK5
WORK6=>M%WORK6
WORK7=>M%WORK7
WORK8=>M%WORK8
WORK9=>M%WORK9
IWORK1=>M%IWORK1
PWORK1=>M%PWORK1
PWORK2=>M%PWORK2
PWORK3=>M%PWORK3
PWORK4=>M%PWORK4
PWORK5=>M%PWORK5
PWORK6=>M%PWORK6
PWORK7=>M%PWORK7
PWORK8=>M%PWORK8
TURB_WORK1=>M%TURB_WORK1
TURB_WORK2=>M%TURB_WORK2
TURB_WORK3=>M%TURB_WORK3
TURB_WORK4=>M%TURB_WORK4
TURB_WORK5=>M%TURB_WORK5
TURB_WORK6=>M%TURB_WORK6
TURB_WORK7=>M%TURB_WORK7
TURB_WORK8=>M%TURB_WORK8
TURB_WORK9=>M%TURB_WORK9
TURB_WORK10=>M%TURB_WORK10
IBM_SAVE1=>M%IBM_SAVE1
IBM_SAVE2=>M%IBM_SAVE2
IBM_SAVE3=>M%IBM_SAVE3
IBM_SAVE4=>M%IBM_SAVE4
IBM_SAVE5=>M%IBM_SAVE5
IBM_SAVE6=>M%IBM_SAVE6
U_MASK=>M%U_MASK
V_MASK=>M%V_MASK
W_MASK=>M%W_MASK
P_MASK=>M%P_MASK
MESH_LEVEL=>M%MESH_LEVEL
WALL_WORK1=>M%WALL_WORK1
WALL_WORK2=>M%WALL_WORK2
QQ=>M%QQ
PP=>M%PP
PPN=>M%PPN
BNDF_TIME_INTEGRAL=>M%BNDF_TIME_INTEGRAL
IBK=>M%IBK
IBLK=>M%IBLK
CFL=>M%CFL
DIVMX=>M%DIVMX
VN=>M%VN
RESMAX=>M%RESMAX
DIVMN=>M%DIVMN
PART_UVWMAX=>M%PART_UVWMAX
DRAG_CFL=>M%DRAG_CFL
ICFL=>M%ICFL
JCFL=>M%JCFL
KCFL=>M%KCFL
IMX=>M%IMX
JMX=>M%JMX
KMX=>M%KMX
IMN=>M%IMN
JMN=>M%JMN
KMN=>M%KMN
IRM=>M%IRM
JRM=>M%JRM
KRM=>M%KRM
IUVW=>M%IUVW
I_VN=>M%I_VN
J_VN=>M%J_VN
K_VN=>M%K_VN
N_EDGES=>M%N_EDGES
IJKE=>M%IJKE
EDGE_INDEX=>M%EDGE_INDEX
TAU_E=>M%TAU_E
OME_E=>M%OME_E
IBAR=>M%IBAR
JBAR=>M%JBAR
KBAR=>M%KBAR
IBM1=>M%IBM1
JBM1=>M%JBM1
KBM1=>M%KBM1
IBP1=>M%IBP1
JBP1=>M%JBP1
KBP1=>M%KBP1
N_NEIGHBORING_MESHES=>M%N_NEIGHBORING_MESHES
NEIGHBORING_MESH=>M%NEIGHBORING_MESH
RGB=>M%RGB
DXI=>M%DXI
DETA=>M%DETA
DZETA=>M%DZETA
RDXI=>M%RDXI
RDETA=>M%RDETA
RDZETA=>M%RDZETA
DXMIN=>M%DXMIN
DXMAX=>M%DXMAX
DYMIN=>M%DYMIN
DYMAX=>M%DYMAX
DZMIN=>M%DZMIN
DZMAX=>M%DZMAX
CELL_SIZE=>M%CELL_SIZE
XS=>M%XS
XF=>M%XF
YS=>M%YS
YF=>M%YF
ZS=>M%ZS
ZF=>M%ZF
RDXINT=>M%RDXINT
RDYINT=>M%RDYINT
RDZINT=>M%RDZINT
R=>M%R
RC=>M%RC
X=>M%X
Y=>M%Y
Z=>M%Z
XC=>M%XC
YC=>M%YC
ZC=>M%ZC
HX=>M%HX
HY=>M%HY
HZ=>M%HZ
DX=>M%DX
DY=>M%DY
DZ=>M%DZ
DXN=>M%DXN
DYN=>M%DYN
DZN=>M%DZN
RDX=>M%RDX
RDY=>M%RDY
RDZ=>M%RDZ
RDXN=>M%RDXN
RDYN=>M%RDYN
RDZN=>M%RDZN
CELLSI=>M%CELLSI
CELLSJ=>M%CELLSJ
CELLSK=>M%CELLSK
RRN=>M%RRN
XPLT=>M%XPLT
YPLT=>M%YPLT
ZPLT=>M%ZPLT
N_OBST=>M%N_OBST
OBSTRUCTION=>M%OBSTRUCTION
N_VENT=>M%N_VENT
VENTS=>M%VENTS
CELL_INDEX=>M%CELL_INDEX
I_CELL=>M%I_CELL
J_CELL=>M%J_CELL
K_CELL=>M%K_CELL
CUTCELL_INDEX=>M%CUTCELL_INDEX
I_CUTCELL=>M%I_CUTCELL
J_CUTCELL=>M%J_CUTCELL
K_CUTCELL=>M%K_CUTCELL
CUTCELL=>M%CUTCELL
FCVAR=>M%FCVAR
IBM_CUT_FACE=>M%IBM_CUT_FACE
OBST_INDEX_C=>M%OBST_INDEX_C
WALL_INDEX=>M%WALL_INDEX
SOLID=>M%SOLID
EXTERIOR=>M%EXTERIOR
CONNECTED_MESH=>M%CONNECTED_MESH
MEAN_FORCING_CELL=>M%MEAN_FORCING_CELL
N_WALL_CELLS=>M%N_WALL_CELLS
N_WALL_CELLS_DIM=>M%N_WALL_CELLS_DIM
N_INTERNAL_WALL_CELLS=>M%N_INTERNAL_WALL_CELLS
N_EXTERNAL_WALL_CELLS=>M%N_EXTERNAL_WALL_CELLS
WALL_COUNTER=>M%WALL_COUNTER
BC_CLOCK=>M%BC_CLOCK
UVW_SAVE=>M%UVW_SAVE
D_CORR=>M%D_CORR
DS_CORR=>M%DS_CORR
U_GHOST=>M%U_GHOST
V_GHOST=>M%V_GHOST
W_GHOST=>M%W_GHOST
EDGE_INTERPOLATION_FACTOR=>M%EDGE_INTERPOLATION_FACTOR
WALL=>M%WALL
EXTERNAL_WALL=>M%EXTERNAL_WALL
OMESH=>M%OMESH
LAGRANGIAN_PARTICLE =>M%LAGRANGIAN_PARTICLE
PARTICLE_STORAGE =>M%PARTICLE_STORAGE
WALL_STORAGE =>M%WALL_STORAGE
NLP=>M%NLP
NLPDIM=>M%NLPDIM
HUMAN =>M%HUMAN
N_HUMANS=>M%N_HUMANS
N_HUMANS_DIM=>M%N_HUMANS_DIM
HUMAN_GRID =>M%HUMAN_GRID
N_SLCF=>M%N_SLCF
SLICE=>M%SLICE
INC=>M%INC
N_PATCH=>M%N_PATCH
PATCH=>M%PATCH
UIID=>M%UIID
RAD_CALL_COUNTER=>M%RAD_CALL_COUNTER
ANGLE_INC_COUNTER=>M%ANGLE_INC_COUNTER
INTERPOLATED_MESH => M%INTERPOLATED_MESH
STRING=>M%STRING
N_STRINGS=>M%N_STRINGS
N_STRINGS_MAX=>M%N_STRINGS_MAX
!rm ->
!DMPVDT_FM_VEG => M%DMPVDT_FM_VEG
K_AGL_SLICE   => M%K_AGL_SLICE
N_TERRAIN_SLCF=>M%N_TERRAIN_SLCF
VEG_CLOCK_BC  =>M%VEG_CLOCK_BC !surf veg
VEG_DRAG      =>M%VEG_DRAG !bndry fuel momentum drag
LS_Z_TERRAIN  =>M%LS_Z_TERRAIN !terrain height for level set fire spread
!rm <-

END SUBROUTINE POINT_TO_MESH

END MODULE MESH_POINTERS
